-- Insert statements for concentrations
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (1, 'Agronomy', 1, 2);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (2, 'Soil Science', 2, 3);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (3, 'Crop Science', 3, 4);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (4, 'Horticulture', 4, 5);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (5, 'Plant Breeding and Genetics', 5, 6);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (6, 'Plant Pathology', 6, 7);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (7, 'Entomology', 7, 8);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (8, 'Weed Science', 8, 9);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (9, 'Agroecology', 9, 10);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (10, 'Agribusiness Management', 10, 11);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (11, 'Agricultural Economics', 11, 12);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (12, 'Agricultural Engineering', 12, 13);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (13, 'Agricultural Extension and Education', 13, 14);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (14, 'Agricultural Policy', 14, 15);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (15, 'Animal Science', 15, 16);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (16, 'Aquaculture', 16, 17);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (17, 'Dairy Science', 17, 18);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (18, 'Poultry Science', 18, 19);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (19, 'Veterinary Medicine', 19, 20);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (20, 'Food Science and Technology', 20, 21);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (21, 'Sustainable Agriculture', 21, 22);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (22, 'Precision Agriculture', 22, 23);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (23, 'Organic Farming', 23, 24);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (24, 'Hydroponics', 24, 25);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (25, 'Vertical Farming', 25, 26);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (26, 'Urban Agriculture', 26, 27);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (27, 'Agroforestry', 27, 28);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (28, 'Silviculture', 28, 29);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (29, 'Range Management', 29, 30);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (30, 'Pasture Management', 30, 31);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (31, 'Soil Conservation', 31, 32);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (32, 'Water Management', 32, 33);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (33, 'Irrigation Engineering', 33, 34);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (34, 'Drainage Systems', 34, 35);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (35, 'Climate Change Adaptation', 35, 36);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (36, 'Environmental Science', 36, 37);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (37, 'Environmental Engineering', 37, 38);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (38, 'Ecology', 38, 39);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (39, 'Conservation Biology', 39, 40);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (40, 'Wildlife Management', 40, 41);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (41, 'Fisheries Management', 41, 42);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (42, 'Marine Biology', 42, 43);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (43, 'Coastal Management', 43, 44);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (44, 'Environmental Policy', 44, 45);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (45, 'Environmental Health', 45, 46);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (46, 'Environmental Impact Assessment', 46, 47);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (47, 'Ecological Restoration', 47, 48);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (48, 'Wetland Management', 48, 49);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (49, 'Desertification Control', 49, 50);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (50, 'Biodiversity Conservation', 50, 51);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (51, 'Agro-biodiversity', 51, 52);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (52, 'Landscape Architecture', 52, 53);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (53, 'Green Infrastructure', 53, 54);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (54, 'Environmental Law', 54, 55);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (55, 'Soil Microbiology', 55, 56);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (56, 'Plant Physiology', 56, 57);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (57, 'Animal Nutrition', 57, 58);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (58, 'Livestock Production Systems', 58, 59);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (59, 'Rural Sociology', 59, 60);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (60, 'Gender Studies in Agriculture', 60, 61);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (61, 'Indigenous Agriculture', 61, 62);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (62, 'Agro-tourism', 62, 63);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (63, 'Agro-ecotourism', 63, 64);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (64, 'Community Supported Agriculture (CSA)', 64, 65);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (65, 'Farm to Table Movement', 65, 66);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (66, 'Slow Food Movement', 66, 67);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (67, 'Food Security', 67, 68);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (68, 'Food Sovereignty', 68, 69);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (69, 'Agricultural Marketing', 69, 70);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (70, 'Agricultural Finance', 70, 71);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (71, 'Risk Management in Agriculture', 71, 72);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (72, 'Supply Chain Management in Agriculture', 72, 73);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (73, 'Agricultural Biotechnology', 73, 74);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (74, 'Genetically Modified Organisms (GMOs)', 74, 75);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (75, 'Biodynamic Farming', 75, 76);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (76, 'Permaculture', 76, 77);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (77, 'Vermiculture', 77, 78);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (78, 'Integrated Pest Management (IPM)', 78, 79);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (79, 'Biopesticides', 79, 80);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (80, 'Biofertilizers', 80, 81);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (81, 'Renewable Energy in Agriculture', 81, 82);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (82, 'Carbon Farming', 82, 83);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (83, 'Agro-weather Forecasting', 83, 84);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (84, 'Rural Development', 84, 85);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (85, 'Farm Labor Management', 85, 86);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (86, 'Agricultural Robotics and Automation', 86, 87);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (87, 'Smart Farming Technologies', 87, 88);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (88, 'Agroinformatics', 88, 89);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (89, 'Big Data Analytics in Agriculture', 89, 90);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (90, 'Blockchain Technology in Agriculture', 90, 91);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (91, 'Agricultural Education and Communication', 91, 92);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (92, 'Agricultural Journalism', 92, 93);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (93, 'Agricultural Biotechnology Ethics', 93, 94);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (94, 'Remote Sensing in Agriculture', 94, 95);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (95, 'Geographical Information Systems (GIS) in Agriculture', 95, 96);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (96, 'Precision Livestock Farming', 96, 97);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (97, 'Food Waste Management', 97, 98);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (98, 'Post-harvest Technology', 98, 99);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (99, 'Food Safety and Quality Assurance', 99, 100);
INSERT INTO Analyst (analyst_id, concentration, engineer_id, specialist_id) VALUES (100, 'Urban Forestry', 100, 1);
