-- Inserting climate types into the Climate table
INSERT INTO Climate (climate_id, data)
VALUES 
(1, 'Tropical Rainforest Climate'),
(2, 'Tropical Monsoon Climate'),
(3, 'Tropical Savanna Climate'),
(4, 'Hot Desert Climate'),
(5, 'Cold Desert Climate'),
(6, 'Hot Semi-arid Climate'),
(7, 'Cold Semi-arid Climate'),
(8, 'Humid Subtropical Climate'),
(9, 'Marine West Coast Climate'),
(10, 'Subpolar Marine Climate'),
(11, 'Hot-summer Mediterranean Climate'),
(12, 'Warm-summer Mediterranean Climate'),
(13, 'Monsoon-influenced humid subtropical Climate'),
(14, 'Monsoon-influenced marine west coast Climate'),
(15, 'Monsoon-influenced Subpolar Oceanic Climate'),
(16, 'Monsoon-influenced Subpolar Oceanic Climate'),
(17, 'Hot Summer Continental Climate'),
(18, 'Warm Summer Continental Climate'),
(19, 'Subarctic Climate'),
(20, 'Continental Subarctic Climate'),
(21, 'Monsoon-influenced Hot Summer Continental Climate'),
(22, 'Monsoon-influenced Warm Summer Continental Climate'),
(23, 'Monsoon-influenced Subarctic Climate'),
(24, 'Monsoon-influenced Continental Subarctic Climate'),
(25, 'Tundra Climate'),
(26, 'Ice Cap Climate');
