insert into Crop (crop_id, Name, health_id, yield_id) values (1, 'Elongated Bluehearts', 136, 752);
insert into Crop (crop_id, Name, health_id, yield_id) values (2, 'Bloodroot', 36, 140);
insert into Crop (crop_id, Name, health_id, yield_id) values (3, 'Schaffner''s Grasswort', 1, 9);
insert into Crop (crop_id, Name, health_id, yield_id) values (4, 'Cartilage Lichen', 52, 913);
insert into Crop (crop_id, Name, health_id, yield_id) values (5, 'Chewing''s Fescue', 133, 343);
insert into Crop (crop_id, Name, health_id, yield_id) values (6, 'Neslia', 109, 691);
insert into Crop (crop_id, Name, health_id, yield_id) values (7, 'Lanceleaf Blanketflower', 68, 605);
insert into Crop (crop_id, Name, health_id, yield_id) values (8, 'Eucalyptus', 133, 570);
insert into Crop (crop_id, Name, health_id, yield_id) values (9, 'Rocky Mountain Beeplant', 125, 659);
insert into Crop (crop_id, Name, health_id, yield_id) values (10, 'Blue Diamond Cholla', 114, 353);
insert into Crop (crop_id, Name, health_id, yield_id) values (11, 'Alaska Saxifrage', 120, 4);
insert into Crop (crop_id, Name, health_id, yield_id) values (12, 'Wavyleaf Noseburn', 28, 67);
insert into Crop (crop_id, Name, health_id, yield_id) values (13, 'Neckera Moss', 11, 532);
insert into Crop (crop_id, Name, health_id, yield_id) values (14, 'Calyptocarpus', 141, 489);
insert into Crop (crop_id, Name, health_id, yield_id) values (15, 'Crandall''s Wild Hollyhock', 13, 39);
insert into Crop (crop_id, Name, health_id, yield_id) values (16, 'Navajo Mountain Phlox', 124, 872);
insert into Crop (crop_id, Name, health_id, yield_id) values (17, 'Twigrush', 104, 623);
insert into Crop (crop_id, Name, health_id, yield_id) values (18, 'Chicoryleaf Wirelettuce', 125, 445);
insert into Crop (crop_id, Name, health_id, yield_id) values (19, 'Purple Threeawn', 142, 534);
insert into Crop (crop_id, Name, health_id, yield_id) values (20, 'Cochlearia', 57, 794);
insert into Crop (crop_id, Name, health_id, yield_id) values (21, 'Hutton''s Dewberry', 74, 857);
insert into Crop (crop_id, Name, health_id, yield_id) values (22, 'Roundpod St. Johnswort', 97, 577);
insert into Crop (crop_id, Name, health_id, yield_id) values (23, 'Hillside Gooseberry', 113, 955);
insert into Crop (crop_id, Name, health_id, yield_id) values (24, 'Scarlet Runner', 114, 418);
insert into Crop (crop_id, Name, health_id, yield_id) values (25, 'Necklace Island Spleenwort', 37, 806);
insert into Crop (crop_id, Name, health_id, yield_id) values (26, 'Low Beardtongue', 39, 513);
insert into Crop (crop_id, Name, health_id, yield_id) values (27, 'Scarlet Bugler', 13, 329);
insert into Crop (crop_id, Name, health_id, yield_id) values (28, 'Seaweed Lichen', 45, 551);
insert into Crop (crop_id, Name, health_id, yield_id) values (29, 'Mojave Pricklypoppy', 17, 273);
insert into Crop (crop_id, Name, health_id, yield_id) values (30, 'Thinleaf Cottonsedge', 139, 69);
insert into Crop (crop_id, Name, health_id, yield_id) values (31, 'Virginia Wildrye', 102, 392);
insert into Crop (crop_id, Name, health_id, yield_id) values (32, 'Hybrid Pitcherplant', 64, 978);
insert into Crop (crop_id, Name, health_id, yield_id) values (33, 'Hiiaka', 44, 464);
insert into Crop (crop_id, Name, health_id, yield_id) values (34, 'Rabbitbrush', 113, 688);
insert into Crop (crop_id, Name, health_id, yield_id) values (35, 'True Babystars', 27, 636);
insert into Crop (crop_id, Name, health_id, yield_id) values (36, 'Stylophorum', 18, 760);
insert into Crop (crop_id, Name, health_id, yield_id) values (37, 'Alumroot Brookfoam', 54, 599);
insert into Crop (crop_id, Name, health_id, yield_id) values (38, 'Tufted Bulrush', 135, 654);
insert into Crop (crop_id, Name, health_id, yield_id) values (39, 'Saltmeadow Cordgrass', 120, 388);
insert into Crop (crop_id, Name, health_id, yield_id) values (40, 'Large Camas', 134, 116);
insert into Crop (crop_id, Name, health_id, yield_id) values (41, 'Robust Clubmoss', 38, 637);
insert into Crop (crop_id, Name, health_id, yield_id) values (42, 'Coast Agropogon', 119, 270);
insert into Crop (crop_id, Name, health_id, yield_id) values (43, 'Plateilema', 65, 980);
insert into Crop (crop_id, Name, health_id, yield_id) values (44, 'Iowa Moonwort', 11, 521);
insert into Crop (crop_id, Name, health_id, yield_id) values (45, 'Tomato Fern', 30, 505);
insert into Crop (crop_id, Name, health_id, yield_id) values (46, 'Pacific Dewberry', 1, 535);
insert into Crop (crop_id, Name, health_id, yield_id) values (47, 'Chamaelirium', 133, 169);
insert into Crop (crop_id, Name, health_id, yield_id) values (48, 'Rocklettuce', 109, 912);
insert into Crop (crop_id, Name, health_id, yield_id) values (49, 'Bolander''s Woodland-star', 108, 703);
insert into Crop (crop_id, Name, health_id, yield_id) values (50, 'Host Sedge', 76, 516);
insert into Crop (crop_id, Name, health_id, yield_id) values (51, 'Coastal Lipfern', 4, 334);
insert into Crop (crop_id, Name, health_id, yield_id) values (52, 'Four-stamen Tamarisk', 29, 615);
insert into Crop (crop_id, Name, health_id, yield_id) values (53, 'Woolly Locoweed', 5, 695);
insert into Crop (crop_id, Name, health_id, yield_id) values (54, 'Curvepod Yellowcress', 140, 977);
insert into Crop (crop_id, Name, health_id, yield_id) values (55, 'Vervain', 47, 864);
insert into Crop (crop_id, Name, health_id, yield_id) values (56, 'Pacific Rim Lichen', 51, 43);
insert into Crop (crop_id, Name, health_id, yield_id) values (57, 'Nuttall''s Toothwort', 69, 173);
insert into Crop (crop_id, Name, health_id, yield_id) values (58, 'Bitter Lettuce', 59, 676);
insert into Crop (crop_id, Name, health_id, yield_id) values (59, 'Kilauea Hau Kuahiwi', 51, 563);
insert into Crop (crop_id, Name, health_id, yield_id) values (60, 'Asia Minor Bluegrass', 135, 131);
insert into Crop (crop_id, Name, health_id, yield_id) values (61, 'Cushion Phlox', 29, 761);
insert into Crop (crop_id, Name, health_id, yield_id) values (62, 'Heartleaf Foamflower', 150, 340);
insert into Crop (crop_id, Name, health_id, yield_id) values (63, 'Glandular Yellow Phacelia', 57, 195);
insert into Crop (crop_id, Name, health_id, yield_id) values (64, 'Fendlerbush', 22, 128);
insert into Crop (crop_id, Name, health_id, yield_id) values (65, 'Spoonsepal Spineflower', 123, 342);
insert into Crop (crop_id, Name, health_id, yield_id) values (66, 'Annual Wildrice', 90, 777);
insert into Crop (crop_id, Name, health_id, yield_id) values (67, 'Neofuscelia Lichen', 99, 597);
insert into Crop (crop_id, Name, health_id, yield_id) values (68, 'Curly Plumeless Thistle', 127, 628);
insert into Crop (crop_id, Name, health_id, yield_id) values (69, 'Java Plum', 72, 741);
insert into Crop (crop_id, Name, health_id, yield_id) values (70, 'Needle And Thread', 20, 323);
insert into Crop (crop_id, Name, health_id, yield_id) values (71, 'Cuban Beaksedge', 138, 179);
insert into Crop (crop_id, Name, health_id, yield_id) values (72, 'Byrsonima', 48, 74);
insert into Crop (crop_id, Name, health_id, yield_id) values (73, 'Ama''u', 90, 22);
insert into Crop (crop_id, Name, health_id, yield_id) values (74, 'Richwoods Sedge', 134, 58);
insert into Crop (crop_id, Name, health_id, yield_id) values (75, 'Diamond-flowers', 9, 360);
insert into Crop (crop_id, Name, health_id, yield_id) values (76, 'Arctic Rattlebox', 78, 541);
insert into Crop (crop_id, Name, health_id, yield_id) values (77, 'California Helianthella', 54, 712);
insert into Crop (crop_id, Name, health_id, yield_id) values (78, 'Elegant Stitchwort', 131, 854);
insert into Crop (crop_id, Name, health_id, yield_id) values (79, 'Harris'' Goldenrod', 146, 485);
insert into Crop (crop_id, Name, health_id, yield_id) values (80, 'Whorled Rosinweed', 44, 87);
insert into Crop (crop_id, Name, health_id, yield_id) values (81, 'Hybrid Rose', 102, 183);
insert into Crop (crop_id, Name, health_id, yield_id) values (82, 'Blue Lawngrass', 110, 744);
insert into Crop (crop_id, Name, health_id, yield_id) values (83, 'Southern Blueberry', 98, 955);
insert into Crop (crop_id, Name, health_id, yield_id) values (84, 'Thorne''s Sedge', 144, 687);
insert into Crop (crop_id, Name, health_id, yield_id) values (85, 'Punctelia', 30, 386);
insert into Crop (crop_id, Name, health_id, yield_id) values (86, 'Saussurea', 27, 737);
insert into Crop (crop_id, Name, health_id, yield_id) values (87, 'Lempholemma Lichen', 142, 301);
insert into Crop (crop_id, Name, health_id, yield_id) values (88, 'Bladder Pod', 38, 912);
insert into Crop (crop_id, Name, health_id, yield_id) values (89, 'Stenocereus', 114, 959);
insert into Crop (crop_id, Name, health_id, yield_id) values (90, 'Trypelthelium Lichen', 73, 994);
insert into Crop (crop_id, Name, health_id, yield_id) values (91, 'Beaked Hawksbeard', 79, 563);
insert into Crop (crop_id, Name, health_id, yield_id) values (92, 'Giant Fescue', 40, 40);
insert into Crop (crop_id, Name, health_id, yield_id) values (93, 'Jasmine Tobacco', 61, 675);
insert into Crop (crop_id, Name, health_id, yield_id) values (94, 'Sandbog Deathcamas', 120, 307);
insert into Crop (crop_id, Name, health_id, yield_id) values (95, 'Florida Yellowtops', 44, 355);
insert into Crop (crop_id, Name, health_id, yield_id) values (96, 'Broadpod Nicker', 87, 283);
insert into Crop (crop_id, Name, health_id, yield_id) values (97, 'Hoffmann''s Buckwheat', 48, 481);
insert into Crop (crop_id, Name, health_id, yield_id) values (98, 'Skyflower', 90, 772);
insert into Crop (crop_id, Name, health_id, yield_id) values (99, 'Garden Yellowrocket', 99, 427);
insert into Crop (crop_id, Name, health_id, yield_id) values (100, 'Torreya', 72, 54);
insert into Crop (crop_id, Name, health_id, yield_id) values (101, '''oha Wai Nui', 25, 69);
insert into Crop (crop_id, Name, health_id, yield_id) values (102, 'Cracked Lichen', 121, 103);
insert into Crop (crop_id, Name, health_id, yield_id) values (103, 'Yerba Neto Hoja De Cueva', 127, 137);
insert into Crop (crop_id, Name, health_id, yield_id) values (104, 'Schweinitz''s Sunflower', 66, 562);
insert into Crop (crop_id, Name, health_id, yield_id) values (105, 'Creeping Treefern', 16, 486);
insert into Crop (crop_id, Name, health_id, yield_id) values (106, 'Mona Island Thoroughwort', 94, 314);
insert into Crop (crop_id, Name, health_id, yield_id) values (107, 'Dwarf False Indigo', 129, 145);
insert into Crop (crop_id, Name, health_id, yield_id) values (108, 'Fendler''s False Cloak Fern', 138, 155);
insert into Crop (crop_id, Name, health_id, yield_id) values (109, 'Robbins'' Milkvetch', 20, 152);
insert into Crop (crop_id, Name, health_id, yield_id) values (110, 'Sentrypalm', 114, 460);
insert into Crop (crop_id, Name, health_id, yield_id) values (111, 'Noel''s Owl''s-clover', 64, 305);
insert into Crop (crop_id, Name, health_id, yield_id) values (112, 'Rose Meadowsweet', 2, 663);
insert into Crop (crop_id, Name, health_id, yield_id) values (113, 'Striped Toadflax', 115, 673);
insert into Crop (crop_id, Name, health_id, yield_id) values (114, 'Pilo', 91, 219);
insert into Crop (crop_id, Name, health_id, yield_id) values (115, 'Mock Bluestem', 17, 160);
insert into Crop (crop_id, Name, health_id, yield_id) values (116, 'Oregon Eurhynchium Moss', 96, 800);
insert into Crop (crop_id, Name, health_id, yield_id) values (117, 'Shinner''s Sedge', 78, 153);
insert into Crop (crop_id, Name, health_id, yield_id) values (118, 'Jazmin De Trapo', 139, 349);
insert into Crop (crop_id, Name, health_id, yield_id) values (119, 'Wildrice', 113, 10);
insert into Crop (crop_id, Name, health_id, yield_id) values (120, 'Charlock Mustard', 19, 659);
insert into Crop (crop_id, Name, health_id, yield_id) values (121, 'Smallflower Mock Buckthorn', 72, 509);
insert into Crop (crop_id, Name, health_id, yield_id) values (122, 'Garden Tomato', 83, 767);
insert into Crop (crop_id, Name, health_id, yield_id) values (123, 'Pursh Seepweed', 9, 453);
insert into Crop (crop_id, Name, health_id, yield_id) values (124, 'Largeleaf Grass Of Parnassus', 71, 461);
insert into Crop (crop_id, Name, health_id, yield_id) values (125, 'Lo''ulu Lelo', 35, 596);
insert into Crop (crop_id, Name, health_id, yield_id) values (126, 'Wallace''s Tobacco', 19, 395);
insert into Crop (crop_id, Name, health_id, yield_id) values (127, 'Russian Olive', 83, 69);
insert into Crop (crop_id, Name, health_id, yield_id) values (128, 'Slenderstem Monkeyflower', 28, 431);
insert into Crop (crop_id, Name, health_id, yield_id) values (129, 'Pinaleno Mountain Rubberweed', 66, 886);
insert into Crop (crop_id, Name, health_id, yield_id) values (130, 'Cliffbrake', 93, 851);
insert into Crop (crop_id, Name, health_id, yield_id) values (131, 'Wild Indigo', 41, 53);
insert into Crop (crop_id, Name, health_id, yield_id) values (132, 'Beachstar', 139, 220);
insert into Crop (crop_id, Name, health_id, yield_id) values (133, 'Limestoneglade Bladderpod', 48, 761);
insert into Crop (crop_id, Name, health_id, yield_id) values (134, 'Paddo Rockcress', 116, 878);
insert into Crop (crop_id, Name, health_id, yield_id) values (135, 'Forked Jelly Lichen', 107, 191);
insert into Crop (crop_id, Name, health_id, yield_id) values (136, 'Elegant Indian Paintbrush', 125, 625);
insert into Crop (crop_id, Name, health_id, yield_id) values (137, 'Hemlock Dwarf Mistletoe', 66, 750);
insert into Crop (crop_id, Name, health_id, yield_id) values (138, 'Rooibos', 79, 89);
insert into Crop (crop_id, Name, health_id, yield_id) values (139, 'Hellebore', 20, 291);
insert into Crop (crop_id, Name, health_id, yield_id) values (140, 'Parks'' Beeblossom', 32, 239);
insert into Crop (crop_id, Name, health_id, yield_id) values (141, 'Goldback Fern', 100, 151);
insert into Crop (crop_id, Name, health_id, yield_id) values (142, 'Awl-leaf Pincushionplant', 2, 851);
insert into Crop (crop_id, Name, health_id, yield_id) values (143, 'Blue Pygmyflower', 69, 411);
insert into Crop (crop_id, Name, health_id, yield_id) values (144, 'Hampton False Foxglove', 116, 488);
insert into Crop (crop_id, Name, health_id, yield_id) values (145, 'Beard Lichen', 33, 987);
insert into Crop (crop_id, Name, health_id, yield_id) values (146, 'Sand Fringepod', 104, 569);
insert into Crop (crop_id, Name, health_id, yield_id) values (147, 'Eggleaf Spurge', 83, 720);
insert into Crop (crop_id, Name, health_id, yield_id) values (148, 'Variableleaf Yellowcress', 17, 719);
insert into Crop (crop_id, Name, health_id, yield_id) values (149, 'Slender Beaksedge', 52, 901);
insert into Crop (crop_id, Name, health_id, yield_id) values (150, 'Thimbleberry', 30, 338);
insert into Crop (crop_id, Name, health_id, yield_id) values (151, 'Timberline Sagebrush', 50, 743);
insert into Crop (crop_id, Name, health_id, yield_id) values (152, 'Mealy Fumewort', 103, 673);
insert into Crop (crop_id, Name, health_id, yield_id) values (153, 'Largeflowered Wintergreen', 128, 487);
insert into Crop (crop_id, Name, health_id, yield_id) values (154, 'Daffodil', 140, 393);
insert into Crop (crop_id, Name, health_id, yield_id) values (155, 'Charleston Mountain Silverbush', 99, 385);
insert into Crop (crop_id, Name, health_id, yield_id) values (156, 'Steyermark''s Milkwort', 135, 514);
insert into Crop (crop_id, Name, health_id, yield_id) values (157, 'Lawn Marshpennywort', 111, 407);
insert into Crop (crop_id, Name, health_id, yield_id) values (158, 'Wright''s Waterwillow', 67, 359);
insert into Crop (crop_id, Name, health_id, yield_id) values (159, 'Keck''s Phacelia', 8, 334);
insert into Crop (crop_id, Name, health_id, yield_id) values (160, 'Dot Lichen', 19, 492);
insert into Crop (crop_id, Name, health_id, yield_id) values (161, 'Coastal Phacelia', 150, 61);
insert into Crop (crop_id, Name, health_id, yield_id) values (162, 'Clasping Jewelflower', 65, 348);
insert into Crop (crop_id, Name, health_id, yield_id) values (163, 'Cup Lichen', 93, 145);
insert into Crop (crop_id, Name, health_id, yield_id) values (164, 'Forest Spleenwort', 36, 14);
insert into Crop (crop_id, Name, health_id, yield_id) values (165, 'Garrett''s Firechalice', 142, 304);
insert into Crop (crop_id, Name, health_id, yield_id) values (166, 'Greenland Buttercup', 67, 180);
insert into Crop (crop_id, Name, health_id, yield_id) values (167, 'Kittentail', 141, 985);
insert into Crop (crop_id, Name, health_id, yield_id) values (168, 'Houghton''s Sedge', 148, 641);
insert into Crop (crop_id, Name, health_id, yield_id) values (169, 'Ixora', 139, 123);
insert into Crop (crop_id, Name, health_id, yield_id) values (170, 'Colorado Greenthread', 85, 877);
insert into Crop (crop_id, Name, health_id, yield_id) values (171, 'Tissueleaf Hawthorn', 37, 295);
insert into Crop (crop_id, Name, health_id, yield_id) values (172, 'Common Duckmeat', 79, 434);
insert into Crop (crop_id, Name, health_id, yield_id) values (173, 'Barberry', 90, 516);
insert into Crop (crop_id, Name, health_id, yield_id) values (174, 'American Hornbeam', 7, 747);
insert into Crop (crop_id, Name, health_id, yield_id) values (175, 'Chinalaurel', 128, 974);
insert into Crop (crop_id, Name, health_id, yield_id) values (176, 'White Screwstem', 145, 808);
insert into Crop (crop_id, Name, health_id, yield_id) values (177, 'Grizzlybear Pricklypear', 107, 275);
insert into Crop (crop_id, Name, health_id, yield_id) values (178, 'Calycera', 88, 573);
insert into Crop (crop_id, Name, health_id, yield_id) values (179, 'Lobed Phaeographis', 124, 381);
insert into Crop (crop_id, Name, health_id, yield_id) values (180, 'Drummond''s Clematis', 72, 911);
insert into Crop (crop_id, Name, health_id, yield_id) values (181, 'Different-nerve Sedge', 24, 892);
insert into Crop (crop_id, Name, health_id, yield_id) values (182, 'Turnor''s Willow', 51, 172);
insert into Crop (crop_id, Name, health_id, yield_id) values (183, 'Sierra Pea', 133, 89);
insert into Crop (crop_id, Name, health_id, yield_id) values (184, 'Weber''s Draba', 119, 927);
insert into Crop (crop_id, Name, health_id, yield_id) values (185, 'San Jacinto Lupine', 118, 222);
insert into Crop (crop_id, Name, health_id, yield_id) values (186, 'Yellow Rabbitbrush', 2, 711);
insert into Crop (crop_id, Name, health_id, yield_id) values (187, 'Fuscidea Lichen', 142, 757);
insert into Crop (crop_id, Name, health_id, yield_id) values (188, 'Slender Hop Clover', 52, 917);
insert into Crop (crop_id, Name, health_id, yield_id) values (189, 'Pygmy Fameflower', 79, 160);
insert into Crop (crop_id, Name, health_id, yield_id) values (190, 'Falfurrias Milkvine', 22, 412);
insert into Crop (crop_id, Name, health_id, yield_id) values (191, 'Gypsum Centaury', 83, 908);
insert into Crop (crop_id, Name, health_id, yield_id) values (192, 'Twisted Airplant', 115, 312);
insert into Crop (crop_id, Name, health_id, yield_id) values (193, 'Roundleaf Stork''s Bill', 98, 295);
insert into Crop (crop_id, Name, health_id, yield_id) values (194, 'Nootka Lupine', 137, 671);
insert into Crop (crop_id, Name, health_id, yield_id) values (195, 'Veronicaleaf Brickellbush', 114, 628);
insert into Crop (crop_id, Name, health_id, yield_id) values (196, 'Common Screwpine', 2, 127);
insert into Crop (crop_id, Name, health_id, yield_id) values (197, 'Russian Thistle', 138, 670);
insert into Crop (crop_id, Name, health_id, yield_id) values (198, 'Shoals Spiderlily', 121, 201);
insert into Crop (crop_id, Name, health_id, yield_id) values (199, 'Bog Goldenrod', 138, 830);
insert into Crop (crop_id, Name, health_id, yield_id) values (200, 'Seaside Goldfields', 22, 257);
insert into Crop (crop_id, Name, health_id, yield_id) values (201, 'Tehachapi Linanthus', 103, 421);
insert into Crop (crop_id, Name, health_id, yield_id) values (202, 'Threeseed Croton', 39, 327);
insert into Crop (crop_id, Name, health_id, yield_id) values (203, 'Pitcherplant', 140, 421);
insert into Crop (crop_id, Name, health_id, yield_id) values (204, 'Atrichum Moss', 83, 712);
insert into Crop (crop_id, Name, health_id, yield_id) values (205, 'Johnny-tuck', 108, 639);
insert into Crop (crop_id, Name, health_id, yield_id) values (206, 'Large Gray Willow', 74, 821);
insert into Crop (crop_id, Name, health_id, yield_id) values (207, 'Bristly Mousetail', 106, 28);
insert into Crop (crop_id, Name, health_id, yield_id) values (208, 'Lavaflow Nehe', 135, 803);
insert into Crop (crop_id, Name, health_id, yield_id) values (209, 'Scented Senna', 129, 863);
insert into Crop (crop_id, Name, health_id, yield_id) values (210, 'Mountain Deathcamas', 109, 552);
insert into Crop (crop_id, Name, health_id, yield_id) values (211, 'Littleflower Alumroot', 64, 483);
insert into Crop (crop_id, Name, health_id, yield_id) values (212, 'Nettleleaf Noseburn', 36, 737);
insert into Crop (crop_id, Name, health_id, yield_id) values (213, 'Arctic Catchfly', 99, 559);
insert into Crop (crop_id, Name, health_id, yield_id) values (214, 'Small Yellow Nicker', 27, 538);
insert into Crop (crop_id, Name, health_id, yield_id) values (215, 'Cuddy Mountain Onion', 121, 137);
insert into Crop (crop_id, Name, health_id, yield_id) values (216, 'Cottonflower', 63, 761);
insert into Crop (crop_id, Name, health_id, yield_id) values (217, 'Maroon Carolina Milkvine', 144, 833);
insert into Crop (crop_id, Name, health_id, yield_id) values (218, 'Rim Lichen', 141, 634);
insert into Crop (crop_id, Name, health_id, yield_id) values (219, 'Kurile Larch', 53, 517);
insert into Crop (crop_id, Name, health_id, yield_id) values (220, 'Bryocaulon Lichen', 149, 44);
insert into Crop (crop_id, Name, health_id, yield_id) values (221, 'California Amaranth', 112, 888);
insert into Crop (crop_id, Name, health_id, yield_id) values (222, 'Rhodotypos', 66, 401);
insert into Crop (crop_id, Name, health_id, yield_id) values (223, 'Sphinctospermum', 66, 227);
insert into Crop (crop_id, Name, health_id, yield_id) values (224, 'Narrowleaf Milkvetch', 140, 964);
insert into Crop (crop_id, Name, health_id, yield_id) values (225, 'Drepanocladus Moss', 60, 883);
insert into Crop (crop_id, Name, health_id, yield_id) values (226, 'Sweet-nancy', 102, 603);
insert into Crop (crop_id, Name, health_id, yield_id) values (227, 'Waialeale Cheesewood', 118, 337);
insert into Crop (crop_id, Name, health_id, yield_id) values (228, 'Sturt''s Cassia', 65, 227);
insert into Crop (crop_id, Name, health_id, yield_id) values (229, 'Orange Daisy', 51, 184);
insert into Crop (crop_id, Name, health_id, yield_id) values (230, 'Naked Buckwheat', 73, 462);
insert into Crop (crop_id, Name, health_id, yield_id) values (231, 'Narrowleaf Brickellbush', 65, 50);
insert into Crop (crop_id, Name, health_id, yield_id) values (232, 'Escoba Babosa', 46, 435);
insert into Crop (crop_id, Name, health_id, yield_id) values (233, 'South American Bonnet Orchid', 27, 289);
insert into Crop (crop_id, Name, health_id, yield_id) values (234, 'Eastwood''s Desertparsley', 44, 771);
insert into Crop (crop_id, Name, health_id, yield_id) values (235, 'Bractless Blazingstar', 123, 521);
insert into Crop (crop_id, Name, health_id, yield_id) values (236, 'Western Black Currant', 75, 384);
insert into Crop (crop_id, Name, health_id, yield_id) values (237, 'Coulter''s Brickellbush', 2, 454);
insert into Crop (crop_id, Name, health_id, yield_id) values (238, 'Tea', 39, 239);
insert into Crop (crop_id, Name, health_id, yield_id) values (239, 'Fuscidea Lichen', 61, 531);
insert into Crop (crop_id, Name, health_id, yield_id) values (240, 'Fibraurea', 51, 944);
insert into Crop (crop_id, Name, health_id, yield_id) values (241, 'Silver Mountain Mahogany', 143, 791);
insert into Crop (crop_id, Name, health_id, yield_id) values (242, 'Boccone''s Sandspurry', 119, 248);
insert into Crop (crop_id, Name, health_id, yield_id) values (243, 'Onosma', 28, 748);
insert into Crop (crop_id, Name, health_id, yield_id) values (244, 'Barnacle Lichen', 92, 217);
insert into Crop (crop_id, Name, health_id, yield_id) values (245, 'Colchicum', 135, 282);
insert into Crop (crop_id, Name, health_id, yield_id) values (246, 'Attorney', 148, 198);
insert into Crop (crop_id, Name, health_id, yield_id) values (247, 'Jost Van Dyke''s Indian Mallow', 45, 413);
insert into Crop (crop_id, Name, health_id, yield_id) values (248, 'Big Blue Lilyturf', 20, 607);
insert into Crop (crop_id, Name, health_id, yield_id) values (249, 'Purple Sage', 146, 19);
insert into Crop (crop_id, Name, health_id, yield_id) values (250, 'Elongate Racomitrium Moss', 15, 181);
insert into Crop (crop_id, Name, health_id, yield_id) values (251, 'Dot Lichen', 42, 241);
insert into Crop (crop_id, Name, health_id, yield_id) values (252, 'Soft Goldenaster', 100, 752);
insert into Crop (crop_id, Name, health_id, yield_id) values (253, 'Grand Fringed Gentian', 64, 562);
insert into Crop (crop_id, Name, health_id, yield_id) values (254, 'King''s Lupine', 59, 856);
insert into Crop (crop_id, Name, health_id, yield_id) values (255, 'Southern Mule-ears', 55, 656);
insert into Crop (crop_id, Name, health_id, yield_id) values (256, 'Eucalyptus', 125, 113);
insert into Crop (crop_id, Name, health_id, yield_id) values (257, 'Spring Pygmycudweed', 35, 593);
insert into Crop (crop_id, Name, health_id, yield_id) values (258, 'Erect Pricklypear', 9, 270);
insert into Crop (crop_id, Name, health_id, yield_id) values (259, 'Weld', 25, 272);
insert into Crop (crop_id, Name, health_id, yield_id) values (260, 'Suffocating Clover', 48, 986);
insert into Crop (crop_id, Name, health_id, yield_id) values (261, 'Hygrohypnum Moss', 110, 281);
insert into Crop (crop_id, Name, health_id, yield_id) values (262, 'Arizona Muhly', 77, 831);
insert into Crop (crop_id, Name, health_id, yield_id) values (263, 'Pugnacious Blackberry', 62, 685);
insert into Crop (crop_id, Name, health_id, yield_id) values (264, 'Kellogg''s Dwarf Rush', 57, 88);
insert into Crop (crop_id, Name, health_id, yield_id) values (265, 'Barneby''s Indian Paintbrush', 77, 203);
insert into Crop (crop_id, Name, health_id, yield_id) values (266, 'Aleutian Cress', 122, 10);
insert into Crop (crop_id, Name, health_id, yield_id) values (267, 'Earle''s Fescue', 47, 299);
insert into Crop (crop_id, Name, health_id, yield_id) values (268, 'Cursed Buttercup', 35, 758);
insert into Crop (crop_id, Name, health_id, yield_id) values (269, 'Blue Mountain Beardtongue', 71, 365);
insert into Crop (crop_id, Name, health_id, yield_id) values (270, 'Yellow Birch', 77, 917);
insert into Crop (crop_id, Name, health_id, yield_id) values (271, 'Anderson''s Buttercup', 138, 856);
insert into Crop (crop_id, Name, health_id, yield_id) values (272, 'Loomis'' Yellow Loosestrife', 131, 270);
insert into Crop (crop_id, Name, health_id, yield_id) values (273, 'Saturn Skin Lichen', 66, 830);
insert into Crop (crop_id, Name, health_id, yield_id) values (274, 'Inyo Buckwheat', 97, 855);
insert into Crop (crop_id, Name, health_id, yield_id) values (275, 'Largeleaf Sphagnum', 1, 158);
insert into Crop (crop_id, Name, health_id, yield_id) values (276, 'Moffatt''s Beardtongue', 15, 419);
insert into Crop (crop_id, Name, health_id, yield_id) values (277, 'Small-leaf Squarestem', 107, 931);
insert into Crop (crop_id, Name, health_id, yield_id) values (278, 'Sea Spurge', 22, 629);
insert into Crop (crop_id, Name, health_id, yield_id) values (279, 'Wright''s Amaranth', 19, 37);
insert into Crop (crop_id, Name, health_id, yield_id) values (280, 'Heim''s Desmatodon Moss', 99, 879);
insert into Crop (crop_id, Name, health_id, yield_id) values (281, 'Erigeron Pussytoes', 39, 351);
insert into Crop (crop_id, Name, health_id, yield_id) values (282, 'Spiked Ipomopsis', 103, 798);
insert into Crop (crop_id, Name, health_id, yield_id) values (283, 'Byssoloma Lichen', 13, 933);
insert into Crop (crop_id, Name, health_id, yield_id) values (284, 'Northwestern Twayblade', 114, 126);
insert into Crop (crop_id, Name, health_id, yield_id) values (285, 'Slender Cryptantha', 138, 537);
insert into Crop (crop_id, Name, health_id, yield_id) values (286, 'Mcdougall''s Yellowtops', 110, 716);
insert into Crop (crop_id, Name, health_id, yield_id) values (287, 'Rio Grande Wild Petunia', 66, 302);
insert into Crop (crop_id, Name, health_id, yield_id) values (288, 'Mountain Pepperweed', 108, 276);
insert into Crop (crop_id, Name, health_id, yield_id) values (289, 'Queensland Maple', 20, 771);
insert into Crop (crop_id, Name, health_id, yield_id) values (290, 'Kolokolo', 41, 291);
insert into Crop (crop_id, Name, health_id, yield_id) values (291, 'Clusterspike False Indigo', 43, 627);
insert into Crop (crop_id, Name, health_id, yield_id) values (292, 'Callingcard Vine', 64, 777);
insert into Crop (crop_id, Name, health_id, yield_id) values (293, 'Cotulaleaf Pincushionplant', 7, 314);
insert into Crop (crop_id, Name, health_id, yield_id) values (294, 'Parry''s Sandmat', 1, 145);
insert into Crop (crop_id, Name, health_id, yield_id) values (295, 'Sullivant''s Entodon Moss', 80, 314);
insert into Crop (crop_id, Name, health_id, yield_id) values (296, 'Hedge False Bindweed', 72, 283);
insert into Crop (crop_id, Name, health_id, yield_id) values (297, 'Royal Lipfern', 35, 957);
insert into Crop (crop_id, Name, health_id, yield_id) values (298, 'Stinkbells', 121, 634);
insert into Crop (crop_id, Name, health_id, yield_id) values (299, 'Mountain Tansymustard', 88, 862);
insert into Crop (crop_id, Name, health_id, yield_id) values (300, 'Merckia', 49, 673);
insert into Crop (crop_id, Name, health_id, yield_id) values (301, 'Green Sotol', 2, 907);
insert into Crop (crop_id, Name, health_id, yield_id) values (302, 'Orange Lichen', 34, 119);
insert into Crop (crop_id, Name, health_id, yield_id) values (303, 'Cinnamon Woodfern', 92, 274);
insert into Crop (crop_id, Name, health_id, yield_id) values (304, 'California Brickellbush', 25, 378);
insert into Crop (crop_id, Name, health_id, yield_id) values (305, 'Arizona Rosemallow', 17, 954);
insert into Crop (crop_id, Name, health_id, yield_id) values (306, 'Nuttall''s Linanthus', 42, 629);
insert into Crop (crop_id, Name, health_id, yield_id) values (307, 'Siberian Squill', 11, 655);
insert into Crop (crop_id, Name, health_id, yield_id) values (308, 'Douglas''s Catchfly', 2, 81);
insert into Crop (crop_id, Name, health_id, yield_id) values (309, 'Pygmy Bentspur Orchid', 119, 717);
insert into Crop (crop_id, Name, health_id, yield_id) values (310, 'Shiny Bugseed', 88, 195);
insert into Crop (crop_id, Name, health_id, yield_id) values (311, 'Bolander''s Madia', 28, 854);
insert into Crop (crop_id, Name, health_id, yield_id) values (312, 'Santa Lucia Mint', 57, 955);
insert into Crop (crop_id, Name, health_id, yield_id) values (313, 'Columnea', 83, 674);
insert into Crop (crop_id, Name, health_id, yield_id) values (314, 'Pine Barren Ticktrefoil', 93, 200);
insert into Crop (crop_id, Name, health_id, yield_id) values (315, 'Dwarf Bundleflower', 119, 91);
insert into Crop (crop_id, Name, health_id, yield_id) values (316, 'Calicoplant', 53, 419);
insert into Crop (crop_id, Name, health_id, yield_id) values (317, 'Wedgeleaf', 100, 621);
insert into Crop (crop_id, Name, health_id, yield_id) values (318, 'Burr Sedge', 58, 383);
insert into Crop (crop_id, Name, health_id, yield_id) values (319, 'Pochote', 36, 785);
insert into Crop (crop_id, Name, health_id, yield_id) values (320, 'Standley''s Goosefoot', 111, 62);
insert into Crop (crop_id, Name, health_id, yield_id) values (321, 'Gray Rupturewort', 68, 504);
insert into Crop (crop_id, Name, health_id, yield_id) values (322, 'Longstalk Clover', 123, 6);
insert into Crop (crop_id, Name, health_id, yield_id) values (323, 'Octopus Tree', 45, 288);
insert into Crop (crop_id, Name, health_id, yield_id) values (324, 'Astrothelium Lichen', 44, 616);
insert into Crop (crop_id, Name, health_id, yield_id) values (325, 'Rabbithead Balsamroot', 145, 769);
insert into Crop (crop_id, Name, health_id, yield_id) values (326, 'Neoregelia', 48, 113);
insert into Crop (crop_id, Name, health_id, yield_id) values (327, 'Uluhe', 48, 864);
insert into Crop (crop_id, Name, health_id, yield_id) values (328, 'Santa Clara Thorn-mint', 123, 90);
insert into Crop (crop_id, Name, health_id, yield_id) values (329, 'Broadleaf Aiea', 140, 475);
insert into Crop (crop_id, Name, health_id, yield_id) values (330, 'San Bernardino Larkspur', 66, 839);
insert into Crop (crop_id, Name, health_id, yield_id) values (331, 'Rimularia Lichen', 28, 25);
insert into Crop (crop_id, Name, health_id, yield_id) values (332, 'Desert Rose', 108, 303);
insert into Crop (crop_id, Name, health_id, yield_id) values (333, 'Polyblastia Lichen', 27, 451);
insert into Crop (crop_id, Name, health_id, yield_id) values (334, 'Peanut', 95, 83);
insert into Crop (crop_id, Name, health_id, yield_id) values (335, 'Carolina Fluffgrass', 98, 507);
insert into Crop (crop_id, Name, health_id, yield_id) values (336, 'Debeque Milkvetch', 1, 784);
insert into Crop (crop_id, Name, health_id, yield_id) values (337, 'Cushion Townsend Daisy', 56, 190);
insert into Crop (crop_id, Name, health_id, yield_id) values (338, 'Claspingleaf Wild Cabbage', 115, 757);
insert into Crop (crop_id, Name, health_id, yield_id) values (339, 'Smallflower Miterwort', 40, 990);
insert into Crop (crop_id, Name, health_id, yield_id) values (340, 'Winged Panicgrass', 2, 52);
insert into Crop (crop_id, Name, health_id, yield_id) values (341, 'Lassen Sandverbena', 118, 553);
insert into Crop (crop_id, Name, health_id, yield_id) values (342, 'Shortleaf Blazing Star', 22, 873);
insert into Crop (crop_id, Name, health_id, yield_id) values (343, 'Annual Ragweed', 40, 486);
insert into Crop (crop_id, Name, health_id, yield_id) values (344, 'Mojave Sandwort', 147, 255);
insert into Crop (crop_id, Name, health_id, yield_id) values (345, 'Water Cowbane', 60, 913);
insert into Crop (crop_id, Name, health_id, yield_id) values (346, 'Chilean Cedar', 132, 30);
insert into Crop (crop_id, Name, health_id, yield_id) values (347, 'Cigar Flower', 13, 808);
insert into Crop (crop_id, Name, health_id, yield_id) values (348, 'Thickleaf Yerba Santa', 132, 225);
insert into Crop (crop_id, Name, health_id, yield_id) values (349, 'Peruvian Primrose-willow', 40, 561);
insert into Crop (crop_id, Name, health_id, yield_id) values (350, 'Alpine Tetramolopium', 74, 166);
insert into Crop (crop_id, Name, health_id, yield_id) values (351, 'Evergreen Mock Orange', 146, 898);
insert into Crop (crop_id, Name, health_id, yield_id) values (352, 'Northwest Territory Sedge', 37, 403);
insert into Crop (crop_id, Name, health_id, yield_id) values (353, 'Nuttall''s Crinklemat', 114, 43);
insert into Crop (crop_id, Name, health_id, yield_id) values (354, 'Schimper''s Acaulon Moss', 20, 703);
insert into Crop (crop_id, Name, health_id, yield_id) values (355, 'Acute Blindia Moss', 91, 52);
insert into Crop (crop_id, Name, health_id, yield_id) values (356, 'Cupflower', 87, 726);
insert into Crop (crop_id, Name, health_id, yield_id) values (357, 'Mokihana', 50, 95);
insert into Crop (crop_id, Name, health_id, yield_id) values (358, 'Annual Agoseris', 1, 64);
insert into Crop (crop_id, Name, health_id, yield_id) values (359, 'Coastal Bluff Bentgrass', 52, 180);
insert into Crop (crop_id, Name, health_id, yield_id) values (360, 'Ricinus', 100, 921);
insert into Crop (crop_id, Name, health_id, yield_id) values (361, 'Spoonleaf Cyanea', 120, 18);
insert into Crop (crop_id, Name, health_id, yield_id) values (362, 'Witch''s Hair Lichen', 22, 659);
insert into Crop (crop_id, Name, health_id, yield_id) values (363, 'Manchurian Honeysuckle', 65, 774);
insert into Crop (crop_id, Name, health_id, yield_id) values (364, 'Gooseberry Currant', 94, 484);
insert into Crop (crop_id, Name, health_id, yield_id) values (365, 'Tall Draba', 84, 696);
insert into Crop (crop_id, Name, health_id, yield_id) values (366, 'Jackfruit', 86, 759);
insert into Crop (crop_id, Name, health_id, yield_id) values (367, 'Bryum Moss', 75, 665);
insert into Crop (crop_id, Name, health_id, yield_id) values (368, 'Southwestern Ringstem', 116, 26);
insert into Crop (crop_id, Name, health_id, yield_id) values (369, 'Felt Lichen', 49, 576);
insert into Crop (crop_id, Name, health_id, yield_id) values (370, 'Poison Ash', 15, 580);
insert into Crop (crop_id, Name, health_id, yield_id) values (371, 'Chihuahuan Lovegrass', 21, 690);
insert into Crop (crop_id, Name, health_id, yield_id) values (372, 'Keyflower', 104, 516);
insert into Crop (crop_id, Name, health_id, yield_id) values (373, 'Hygroamblystegium Moss', 22, 928);
insert into Crop (crop_id, Name, health_id, yield_id) values (374, 'Island Orange Lichen', 89, 495);
insert into Crop (crop_id, Name, health_id, yield_id) values (375, 'Netleaf Leather Flower', 46, 538);
insert into Crop (crop_id, Name, health_id, yield_id) values (376, 'Oysterleaf', 69, 6);
insert into Crop (crop_id, Name, health_id, yield_id) values (377, 'Mastic Tree', 20, 105);
insert into Crop (crop_id, Name, health_id, yield_id) values (378, 'Northern False Candytuft', 120, 328);
insert into Crop (crop_id, Name, health_id, yield_id) values (379, 'Chocolate Chip Lichen', 59, 549);
insert into Crop (crop_id, Name, health_id, yield_id) values (380, 'American Wintergreen', 62, 198);
insert into Crop (crop_id, Name, health_id, yield_id) values (381, 'European Columbine', 121, 437);
insert into Crop (crop_id, Name, health_id, yield_id) values (382, 'Santa Susana Tarweed', 24, 923);
insert into Crop (crop_id, Name, health_id, yield_id) values (383, 'Chautle Livingrock', 103, 118);
insert into Crop (crop_id, Name, health_id, yield_id) values (384, 'Timber Milkvetch', 124, 822);
insert into Crop (crop_id, Name, health_id, yield_id) values (385, 'California Desert-thorn', 146, 100);
insert into Crop (crop_id, Name, health_id, yield_id) values (386, 'Waterhorehound', 22, 557);
insert into Crop (crop_id, Name, health_id, yield_id) values (387, 'Oregon Checkerbloom', 150, 97);
insert into Crop (crop_id, Name, health_id, yield_id) values (388, 'Alexandrian Laurel', 150, 868);
insert into Crop (crop_id, Name, health_id, yield_id) values (389, 'Orthotrichum Moss', 24, 48);
insert into Crop (crop_id, Name, health_id, yield_id) values (390, 'Pandanus', 124, 607);
insert into Crop (crop_id, Name, health_id, yield_id) values (391, 'Singlewhorl Burrobrush', 88, 81);
insert into Crop (crop_id, Name, health_id, yield_id) values (392, 'Mountain Pride', 29, 130);
insert into Crop (crop_id, Name, health_id, yield_id) values (393, 'Thouinia', 61, 483);
insert into Crop (crop_id, Name, health_id, yield_id) values (394, 'Lanceleaf Rose Gentian', 116, 151);
insert into Crop (crop_id, Name, health_id, yield_id) values (395, 'Longstalk Holly', 78, 476);
insert into Crop (crop_id, Name, health_id, yield_id) values (396, 'Gray''s Catchfly', 17, 328);
insert into Crop (crop_id, Name, health_id, yield_id) values (397, 'Kern Canyon False Goldenaster', 24, 740);
insert into Crop (crop_id, Name, health_id, yield_id) values (398, 'Widethroat Yellow Monkeyflower', 140, 631);
insert into Crop (crop_id, Name, health_id, yield_id) values (399, 'Western Sweetvetch', 52, 33);
insert into Crop (crop_id, Name, health_id, yield_id) values (400, 'Cape Leadwort', 111, 962);
insert into Crop (crop_id, Name, health_id, yield_id) values (401, '''ena''ena', 96, 354);
insert into Crop (crop_id, Name, health_id, yield_id) values (402, 'Sacapellote', 150, 826);
insert into Crop (crop_id, Name, health_id, yield_id) values (403, 'Longstalk Sedge', 101, 700);
insert into Crop (crop_id, Name, health_id, yield_id) values (404, 'Interior Ironweed', 37, 321);
insert into Crop (crop_id, Name, health_id, yield_id) values (405, 'False Hellebore', 4, 687);
insert into Crop (crop_id, Name, health_id, yield_id) values (406, 'Retem', 96, 949);
insert into Crop (crop_id, Name, health_id, yield_id) values (407, 'Cuero De Rana', 80, 168);
insert into Crop (crop_id, Name, health_id, yield_id) values (408, 'Groovestem Bouchea', 29, 324);
insert into Crop (crop_id, Name, health_id, yield_id) values (409, 'Rimelia Lichen', 17, 360);
insert into Crop (crop_id, Name, health_id, yield_id) values (410, 'Willowleaf Aster', 85, 763);
insert into Crop (crop_id, Name, health_id, yield_id) values (411, 'Lined Bristle Fern', 26, 173);
insert into Crop (crop_id, Name, health_id, yield_id) values (412, 'Woolly Prairie Clover', 5, 299);
insert into Crop (crop_id, Name, health_id, yield_id) values (413, 'Spreading Yellowcress', 26, 915);
insert into Crop (crop_id, Name, health_id, yield_id) values (414, 'Candytuft', 88, 672);
insert into Crop (crop_id, Name, health_id, yield_id) values (415, 'Ortela', 53, 343);
insert into Crop (crop_id, Name, health_id, yield_id) values (416, 'Snowy Mermaid', 141, 265);
insert into Crop (crop_id, Name, health_id, yield_id) values (417, 'Paraleucobryum Moss', 63, 490);
insert into Crop (crop_id, Name, health_id, yield_id) values (418, 'Clusterspike False Indigo', 24, 865);
insert into Crop (crop_id, Name, health_id, yield_id) values (419, 'Splitleaf Indian Paintbrush', 50, 755);
insert into Crop (crop_id, Name, health_id, yield_id) values (420, 'Melanelia Lichen', 9, 258);
insert into Crop (crop_id, Name, health_id, yield_id) values (421, 'Parmotrema Lichen', 45, 850);
insert into Crop (crop_id, Name, health_id, yield_id) values (422, 'Princess Of The Night', 20, 159);
insert into Crop (crop_id, Name, health_id, yield_id) values (423, 'West Indian Starwort', 24, 859);
insert into Crop (crop_id, Name, health_id, yield_id) values (424, 'Cartilage Lichen', 18, 491);
insert into Crop (crop_id, Name, health_id, yield_id) values (425, 'Yellow Alder', 98, 671);
insert into Crop (crop_id, Name, health_id, yield_id) values (426, 'Hybrid Willow', 112, 582);
insert into Crop (crop_id, Name, health_id, yield_id) values (427, 'Texas Star', 43, 37);
insert into Crop (crop_id, Name, health_id, yield_id) values (428, 'Abaca', 110, 517);
insert into Crop (crop_id, Name, health_id, yield_id) values (429, 'Small White Violet', 64, 418);
insert into Crop (crop_id, Name, health_id, yield_id) values (430, 'Beard Lichen', 92, 865);
insert into Crop (crop_id, Name, health_id, yield_id) values (431, 'Tall Silky Lupine', 135, 419);
insert into Crop (crop_id, Name, health_id, yield_id) values (432, 'Golden Chain Tree', 120, 1);
insert into Crop (crop_id, Name, health_id, yield_id) values (433, 'Sierra Tiger Lily', 83, 103);
insert into Crop (crop_id, Name, health_id, yield_id) values (434, 'Apteria', 123, 277);
insert into Crop (crop_id, Name, health_id, yield_id) values (435, 'Draba', 9, 530);
insert into Crop (crop_id, Name, health_id, yield_id) values (436, 'Garden Lovage', 133, 639);
insert into Crop (crop_id, Name, health_id, yield_id) values (437, 'Drymary', 62, 371);
insert into Crop (crop_id, Name, health_id, yield_id) values (438, 'Erect Seaberry', 75, 540);
insert into Crop (crop_id, Name, health_id, yield_id) values (439, 'Smallflower Mock Buckthorn', 124, 396);
insert into Crop (crop_id, Name, health_id, yield_id) values (440, 'Needle Lichen', 56, 503);
insert into Crop (crop_id, Name, health_id, yield_id) values (441, 'Reussia', 21, 451);
insert into Crop (crop_id, Name, health_id, yield_id) values (442, 'Beard Lichen', 31, 488);
insert into Crop (crop_id, Name, health_id, yield_id) values (443, 'Manyflower Rush', 5, 342);
insert into Crop (crop_id, Name, health_id, yield_id) values (444, 'California Sunflower', 150, 270);
insert into Crop (crop_id, Name, health_id, yield_id) values (445, 'Hairy Forked Nailwort', 48, 102);
insert into Crop (crop_id, Name, health_id, yield_id) values (446, 'Great Bladdery Milkvetch', 76, 956);
insert into Crop (crop_id, Name, health_id, yield_id) values (447, 'Newberry''s Lipfern', 38, 907);
insert into Crop (crop_id, Name, health_id, yield_id) values (448, 'Scented Shootingstar', 83, 111);
insert into Crop (crop_id, Name, health_id, yield_id) values (449, 'Dwarf Goldenrod', 49, 202);
insert into Crop (crop_id, Name, health_id, yield_id) values (450, 'Mediterranean Figwort', 124, 466);
insert into Crop (crop_id, Name, health_id, yield_id) values (451, 'Phlyctella Lichen', 12, 191);
insert into Crop (crop_id, Name, health_id, yield_id) values (452, 'Rubber Rabbitbrush', 116, 787);
insert into Crop (crop_id, Name, health_id, yield_id) values (453, 'Tushar Mountain Draba', 79, 583);
insert into Crop (crop_id, Name, health_id, yield_id) values (454, 'Southern Waxy Sedge', 87, 38);
insert into Crop (crop_id, Name, health_id, yield_id) values (455, 'Switchgrass', 110, 496);
insert into Crop (crop_id, Name, health_id, yield_id) values (456, 'Aleutian Selfheal', 117, 566);
insert into Crop (crop_id, Name, health_id, yield_id) values (457, 'Nodding Evening Primrose', 109, 405);
insert into Crop (crop_id, Name, health_id, yield_id) values (458, 'Slender Scratchdaisy', 18, 593);
insert into Crop (crop_id, Name, health_id, yield_id) values (459, 'Artist''s Popcornflower', 85, 929);
insert into Crop (crop_id, Name, health_id, yield_id) values (460, 'Hypnum Moss', 129, 886);
insert into Crop (crop_id, Name, health_id, yield_id) values (461, 'Texas Sunnybell', 19, 819);
insert into Crop (crop_id, Name, health_id, yield_id) values (462, 'Purple Stripeseed', 10, 61);
insert into Crop (crop_id, Name, health_id, yield_id) values (463, 'Hearst''s Manzanita', 149, 746);
insert into Crop (crop_id, Name, health_id, yield_id) values (464, 'Gilman''s Springparsley', 9, 734);
insert into Crop (crop_id, Name, health_id, yield_id) values (465, 'Cuban Jute', 10, 53);
insert into Crop (crop_id, Name, health_id, yield_id) values (466, 'Rubber Rabbitbrush', 7, 185);
insert into Crop (crop_id, Name, health_id, yield_id) values (467, 'Avian Goosefoot', 93, 433);
insert into Crop (crop_id, Name, health_id, yield_id) values (468, 'Moleplant', 99, 375);
insert into Crop (crop_id, Name, health_id, yield_id) values (469, 'Dentnut Cryptantha', 24, 834);
insert into Crop (crop_id, Name, health_id, yield_id) values (470, 'White Crownvetch', 106, 100);
insert into Crop (crop_id, Name, health_id, yield_id) values (471, 'Degel''s Wart Lichen', 84, 963);
insert into Crop (crop_id, Name, health_id, yield_id) values (472, 'Green Rabbitbrush', 20, 599);
insert into Crop (crop_id, Name, health_id, yield_id) values (473, 'Brackenridge''s Rosemallow', 40, 360);
insert into Crop (crop_id, Name, health_id, yield_id) values (474, 'Western Thelomma Lichen', 45, 377);
insert into Crop (crop_id, Name, health_id, yield_id) values (475, 'Anise Burnet Saxifrage', 41, 734);
insert into Crop (crop_id, Name, health_id, yield_id) values (476, 'Hybrid Oak', 75, 910);
insert into Crop (crop_id, Name, health_id, yield_id) values (477, 'Nuttall''s Townsend Daisy', 40, 15);
insert into Crop (crop_id, Name, health_id, yield_id) values (478, 'Hidden Buckwheat', 143, 871);
insert into Crop (crop_id, Name, health_id, yield_id) values (479, 'Spiked Bur Grass', 16, 93);
insert into Crop (crop_id, Name, health_id, yield_id) values (480, 'California Jointfir', 56, 252);
insert into Crop (crop_id, Name, health_id, yield_id) values (481, 'California Xanthoparmelia Lichen', 94, 652);
insert into Crop (crop_id, Name, health_id, yield_id) values (482, 'Quillwort', 4, 212);
insert into Crop (crop_id, Name, health_id, yield_id) values (483, 'Yucca Plum Pine', 31, 821);
insert into Crop (crop_id, Name, health_id, yield_id) values (484, 'Longleaf Starwort', 90, 900);
insert into Crop (crop_id, Name, health_id, yield_id) values (485, 'West African Rubbertree', 129, 41);
insert into Crop (crop_id, Name, health_id, yield_id) values (486, 'Tropical Bent', 63, 185);
insert into Crop (crop_id, Name, health_id, yield_id) values (487, 'Hop', 93, 674);
insert into Crop (crop_id, Name, health_id, yield_id) values (488, 'Mountain Indian Paintbrush', 124, 566);
insert into Crop (crop_id, Name, health_id, yield_id) values (489, 'Bottle-palm', 95, 567);
insert into Crop (crop_id, Name, health_id, yield_id) values (490, 'Japanese Goose Neck Moss', 118, 883);
insert into Crop (crop_id, Name, health_id, yield_id) values (491, 'Paraguayan Windmill Grass', 111, 187);
insert into Crop (crop_id, Name, health_id, yield_id) values (492, 'Smallflower Chastetree', 69, 311);
insert into Crop (crop_id, Name, health_id, yield_id) values (493, 'Fisher''s Tundragrass', 63, 683);
insert into Crop (crop_id, Name, health_id, yield_id) values (494, 'Blackrodwood', 69, 853);
insert into Crop (crop_id, Name, health_id, yield_id) values (495, 'Rim Lichen', 121, 328);
insert into Crop (crop_id, Name, health_id, yield_id) values (496, 'Large Whorled Pogonia', 106, 728);
insert into Crop (crop_id, Name, health_id, yield_id) values (497, 'Snow Gum', 138, 536);
insert into Crop (crop_id, Name, health_id, yield_id) values (498, 'Mojave Milkvetch', 69, 815);
insert into Crop (crop_id, Name, health_id, yield_id) values (499, 'Flaxleaf Fanpetals', 81, 775);
insert into Crop (crop_id, Name, health_id, yield_id) values (500, 'Spiderwisp', 91, 140);
insert into Crop (crop_id, Name, health_id, yield_id) values (501, 'Rupertia', 50, 422);
insert into Crop (crop_id, Name, health_id, yield_id) values (502, 'Snow Lichen', 22, 206);
insert into Crop (crop_id, Name, health_id, yield_id) values (503, 'Alexanders', 39, 19);
insert into Crop (crop_id, Name, health_id, yield_id) values (504, 'Indian Lovegrass', 25, 672);
insert into Crop (crop_id, Name, health_id, yield_id) values (505, 'Flatleaf Flatsedge', 30, 542);
insert into Crop (crop_id, Name, health_id, yield_id) values (506, 'Palo De Hueso', 66, 633);
insert into Crop (crop_id, Name, health_id, yield_id) values (507, 'Water Trumpet', 60, 164);
insert into Crop (crop_id, Name, health_id, yield_id) values (508, 'Sorrie''s Heartleaf', 74, 21);
insert into Crop (crop_id, Name, health_id, yield_id) values (509, 'Prairie Bishop', 47, 809);
insert into Crop (crop_id, Name, health_id, yield_id) values (510, 'Gregg''s Ash', 38, 615);
insert into Crop (crop_id, Name, health_id, yield_id) values (511, 'Little''s Fissidens Moss', 132, 460);
insert into Crop (crop_id, Name, health_id, yield_id) values (512, 'Cordroot Beardtongue', 5, 853);
insert into Crop (crop_id, Name, health_id, yield_id) values (513, 'Alternate-leaf Golden Saxifrage', 38, 531);
insert into Crop (crop_id, Name, health_id, yield_id) values (514, 'Redwood Pea', 112, 814);
insert into Crop (crop_id, Name, health_id, yield_id) values (515, 'Dwarf Checkerbloom', 57, 738);
insert into Crop (crop_id, Name, health_id, yield_id) values (516, 'Hollyleaved Barberry', 130, 584);
insert into Crop (crop_id, Name, health_id, yield_id) values (517, 'Poppy', 130, 620);
insert into Crop (crop_id, Name, health_id, yield_id) values (518, 'Needleleaf Navarretia', 101, 328);
insert into Crop (crop_id, Name, health_id, yield_id) values (519, 'Wheel Milkweed', 58, 52);
insert into Crop (crop_id, Name, health_id, yield_id) values (520, 'Waxyleaf Meadow-rue', 27, 996);
insert into Crop (crop_id, Name, health_id, yield_id) values (521, 'Mexican Bedstraw', 93, 513);
insert into Crop (crop_id, Name, health_id, yield_id) values (522, 'Pyrenopsis Lichen', 149, 765);
insert into Crop (crop_id, Name, health_id, yield_id) values (523, 'Prairie Brazosmint', 38, 955);
insert into Crop (crop_id, Name, health_id, yield_id) values (524, 'Eggyolk Lichen', 37, 156);
insert into Crop (crop_id, Name, health_id, yield_id) values (525, 'Plymouth Blackberry', 129, 353);
insert into Crop (crop_id, Name, health_id, yield_id) values (526, 'Erichsen''s Wart Lichen', 12, 356);
insert into Crop (crop_id, Name, health_id, yield_id) values (527, 'Stryphnodendron', 20, 569);
insert into Crop (crop_id, Name, health_id, yield_id) values (528, 'Molokai Mirrorplant', 88, 387);
insert into Crop (crop_id, Name, health_id, yield_id) values (529, 'Thicket Groundcherry', 59, 753);
insert into Crop (crop_id, Name, health_id, yield_id) values (530, 'Moss Campion', 24, 756);
insert into Crop (crop_id, Name, health_id, yield_id) values (531, 'Broom-like Ragwort', 136, 335);
insert into Crop (crop_id, Name, health_id, yield_id) values (532, 'Rinodina Lichen', 77, 33);
insert into Crop (crop_id, Name, health_id, yield_id) values (533, 'Redflower Currant', 134, 916);
insert into Crop (crop_id, Name, health_id, yield_id) values (534, 'Massachusetts Blackberry', 42, 771);
insert into Crop (crop_id, Name, health_id, yield_id) values (535, 'Beaked Mock Vervain', 121, 826);
insert into Crop (crop_id, Name, health_id, yield_id) values (536, 'Cockleshell Lichen', 145, 385);
insert into Crop (crop_id, Name, health_id, yield_id) values (537, 'Organ Mountain Figwort', 128, 860);
insert into Crop (crop_id, Name, health_id, yield_id) values (538, 'Ballast Toadflax', 6, 932);
insert into Crop (crop_id, Name, health_id, yield_id) values (539, 'Mountain St. Johnswort', 149, 508);
insert into Crop (crop_id, Name, health_id, yield_id) values (540, 'Maleberry', 119, 783);
insert into Crop (crop_id, Name, health_id, yield_id) values (541, 'Soft Popcornflower', 141, 995);
insert into Crop (crop_id, Name, health_id, yield_id) values (542, 'Inyo Milkvetch', 16, 236);
insert into Crop (crop_id, Name, health_id, yield_id) values (543, 'Smallflower Chastetree', 60, 26);
insert into Crop (crop_id, Name, health_id, yield_id) values (544, 'Narrowleaf Queen Poppy', 90, 825);
insert into Crop (crop_id, Name, health_id, yield_id) values (545, 'Leatherstem', 22, 14);
insert into Crop (crop_id, Name, health_id, yield_id) values (546, 'Threepetal Bedstraw', 2, 596);
insert into Crop (crop_id, Name, health_id, yield_id) values (547, 'Texas Heliotrope', 46, 978);
insert into Crop (crop_id, Name, health_id, yield_id) values (548, 'Schreber''s Dicranella Moss', 68, 147);
insert into Crop (crop_id, Name, health_id, yield_id) values (549, 'Thurber''s Pepperweed', 114, 653);
insert into Crop (crop_id, Name, health_id, yield_id) values (550, 'Miriquidica Lichen', 40, 135);
insert into Crop (crop_id, Name, health_id, yield_id) values (551, 'Thelidium Lichen', 32, 938);
insert into Crop (crop_id, Name, health_id, yield_id) values (552, 'Chiricahua Mountain Mudwort', 93, 630);
insert into Crop (crop_id, Name, health_id, yield_id) values (553, 'Rhodotypos', 50, 82);
insert into Crop (crop_id, Name, health_id, yield_id) values (554, 'Derris', 98, 85);
insert into Crop (crop_id, Name, health_id, yield_id) values (555, 'Yellowspine Thistle', 127, 507);
insert into Crop (crop_id, Name, health_id, yield_id) values (556, 'Austrian Draba', 88, 72);
insert into Crop (crop_id, Name, health_id, yield_id) values (557, 'Foothill Deervetch', 130, 495);
insert into Crop (crop_id, Name, health_id, yield_id) values (558, 'Velvetbells', 116, 156);
insert into Crop (crop_id, Name, health_id, yield_id) values (559, 'White Mountain-avens', 44, 480);
insert into Crop (crop_id, Name, health_id, yield_id) values (560, 'Hapu''u Li', 76, 211);
insert into Crop (crop_id, Name, health_id, yield_id) values (561, 'Wrightwort', 3, 314);
insert into Crop (crop_id, Name, health_id, yield_id) values (562, 'Houston Meadow-rue', 46, 167);
insert into Crop (crop_id, Name, health_id, yield_id) values (563, 'Green-flower Clermontia', 114, 161);
insert into Crop (crop_id, Name, health_id, yield_id) values (564, 'Single Delight', 28, 241);
insert into Crop (crop_id, Name, health_id, yield_id) values (565, 'Striated Broom', 100, 848);
insert into Crop (crop_id, Name, health_id, yield_id) values (566, 'Beach Saltbush', 18, 936);
insert into Crop (crop_id, Name, health_id, yield_id) values (567, 'Showy Stickseed', 88, 927);
insert into Crop (crop_id, Name, health_id, yield_id) values (568, 'Woodland Tribisee', 51, 497);
insert into Crop (crop_id, Name, health_id, yield_id) values (569, 'Falseteeth', 5, 806);
insert into Crop (crop_id, Name, health_id, yield_id) values (570, 'Lavaslope Centaury', 16, 959);
insert into Crop (crop_id, Name, health_id, yield_id) values (571, 'American Dragonhead', 28, 169);
insert into Crop (crop_id, Name, health_id, yield_id) values (572, 'California Goldenbanner', 22, 241);
insert into Crop (crop_id, Name, health_id, yield_id) values (573, 'Pale Bastard Toadflax', 11, 856);
insert into Crop (crop_id, Name, health_id, yield_id) values (574, 'Ngmui', 140, 110);
insert into Crop (crop_id, Name, health_id, yield_id) values (575, 'Drooping Wattle', 65, 519);
insert into Crop (crop_id, Name, health_id, yield_id) values (576, 'Purple Locoweed', 34, 606);
insert into Crop (crop_id, Name, health_id, yield_id) values (577, 'Copper Iris', 83, 176);
insert into Crop (crop_id, Name, health_id, yield_id) values (578, 'Arizona Desert Foxglove', 6, 49);
insert into Crop (crop_id, Name, health_id, yield_id) values (579, 'Red-leaf Phyllostegia', 72, 529);
insert into Crop (crop_id, Name, health_id, yield_id) values (580, 'Yerba De Culebra', 147, 905);
insert into Crop (crop_id, Name, health_id, yield_id) values (581, 'Renner''s Map Lichen', 37, 647);
insert into Crop (crop_id, Name, health_id, yield_id) values (582, 'Bulbothrix Lichen', 147, 866);
insert into Crop (crop_id, Name, health_id, yield_id) values (583, 'Tachibana Orange', 145, 865);
insert into Crop (crop_id, Name, health_id, yield_id) values (584, 'Wart Lichen', 106, 9);
insert into Crop (crop_id, Name, health_id, yield_id) values (585, 'Pseudoleskea Moss', 74, 924);
insert into Crop (crop_id, Name, health_id, yield_id) values (586, 'Amorphophallus', 34, 349);
insert into Crop (crop_id, Name, health_id, yield_id) values (587, 'Scalystem', 116, 579);
insert into Crop (crop_id, Name, health_id, yield_id) values (588, 'Panicled Sandmallow', 118, 633);
insert into Crop (crop_id, Name, health_id, yield_id) values (589, 'Tropical Govenia', 126, 317);
insert into Crop (crop_id, Name, health_id, yield_id) values (590, 'Early Yellowrocket', 5, 569);
insert into Crop (crop_id, Name, health_id, yield_id) values (591, 'Huachuca Mountain Lupine', 50, 725);
insert into Crop (crop_id, Name, health_id, yield_id) values (592, 'Riverside Spineflower', 130, 868);
insert into Crop (crop_id, Name, health_id, yield_id) values (593, 'Cold Stigmidium Lichen', 11, 915);
insert into Crop (crop_id, Name, health_id, yield_id) values (594, 'Jepson''s Onion', 61, 239);
insert into Crop (crop_id, Name, health_id, yield_id) values (595, 'Tapered Polypody', 121, 431);
insert into Crop (crop_id, Name, health_id, yield_id) values (596, 'Balloonplant', 36, 312);
insert into Crop (crop_id, Name, health_id, yield_id) values (597, 'Perfoliate Blackfoot', 112, 914);
insert into Crop (crop_id, Name, health_id, yield_id) values (598, 'Kearney''s Sumac', 7, 858);
insert into Crop (crop_id, Name, health_id, yield_id) values (599, 'Roundseed Panicgrass', 40, 281);
insert into Crop (crop_id, Name, health_id, yield_id) values (600, 'Trelease''s Beavertail Pricklypear', 34, 263);
insert into Crop (crop_id, Name, health_id, yield_id) values (601, 'Mother Of Thyme', 100, 66);
insert into Crop (crop_id, Name, health_id, yield_id) values (602, 'Georgia Ironweed', 57, 668);
insert into Crop (crop_id, Name, health_id, yield_id) values (603, 'Partridgefoot', 15, 187);
insert into Crop (crop_id, Name, health_id, yield_id) values (604, 'Siberian Oatgrass', 112, 638);
insert into Crop (crop_id, Name, health_id, yield_id) values (605, 'Tall Blazing Star', 145, 288);
insert into Crop (crop_id, Name, health_id, yield_id) values (606, 'Curtiss'' Milkweed', 34, 93);
insert into Crop (crop_id, Name, health_id, yield_id) values (607, 'Purple Twinpod', 26, 87);
insert into Crop (crop_id, Name, health_id, yield_id) values (608, 'Lecidea Lichen', 54, 90);
insert into Crop (crop_id, Name, health_id, yield_id) values (609, 'Wavyleaf Indian Paintbrush', 100, 521);
insert into Crop (crop_id, Name, health_id, yield_id) values (610, 'Melaspilea Lichen', 140, 490);
insert into Crop (crop_id, Name, health_id, yield_id) values (611, 'Butterflybush', 98, 545);
insert into Crop (crop_id, Name, health_id, yield_id) values (612, 'Northern Hawthorn', 27, 13);
insert into Crop (crop_id, Name, health_id, yield_id) values (613, 'Black Dropseed', 102, 379);
insert into Crop (crop_id, Name, health_id, yield_id) values (614, 'Slickseed Fuzzybean', 140, 509);
insert into Crop (crop_id, Name, health_id, yield_id) values (615, 'Bois Bande', 129, 493);
insert into Crop (crop_id, Name, health_id, yield_id) values (616, 'Sporastatia Lichen', 19, 759);
insert into Crop (crop_id, Name, health_id, yield_id) values (617, 'Chinese Rhubarb', 71, 883);
insert into Crop (crop_id, Name, health_id, yield_id) values (618, 'Lycaste', 127, 404);
insert into Crop (crop_id, Name, health_id, yield_id) values (619, 'Aleutian Wildrye', 128, 751);
insert into Crop (crop_id, Name, health_id, yield_id) values (620, 'Shrubland Nehe', 107, 958);
insert into Crop (crop_id, Name, health_id, yield_id) values (621, 'Salmonberry', 139, 424);
insert into Crop (crop_id, Name, health_id, yield_id) values (622, 'Greenvein Lady''s Tresses', 140, 34);
insert into Crop (crop_id, Name, health_id, yield_id) values (623, 'Broadleaf Monkeyflower', 77, 794);
insert into Crop (crop_id, Name, health_id, yield_id) values (624, 'Small Matweed', 89, 461);
insert into Crop (crop_id, Name, health_id, yield_id) values (625, 'Common Velvetgrass', 65, 1000);
insert into Crop (crop_id, Name, health_id, yield_id) values (626, 'Hazel Alder', 78, 440);
insert into Crop (crop_id, Name, health_id, yield_id) values (627, 'Fineleaf Hymenopappus', 55, 217);
insert into Crop (crop_id, Name, health_id, yield_id) values (628, 'Willowleaf Spleenwort', 135, 469);
insert into Crop (crop_id, Name, health_id, yield_id) values (629, 'Davy''s Clarkia', 30, 129);
insert into Crop (crop_id, Name, health_id, yield_id) values (630, 'Eschweiler''s Pyxine Lichen', 100, 185);
insert into Crop (crop_id, Name, health_id, yield_id) values (631, 'Sugar Maple', 68, 665);
insert into Crop (crop_id, Name, health_id, yield_id) values (632, 'Vriesea', 57, 868);
insert into Crop (crop_id, Name, health_id, yield_id) values (633, 'Bog Willow', 31, 420);
insert into Crop (crop_id, Name, health_id, yield_id) values (634, 'Climbing Dayflower', 5, 800);
insert into Crop (crop_id, Name, health_id, yield_id) values (635, 'Fourwing Saltbush', 27, 333);
insert into Crop (crop_id, Name, health_id, yield_id) values (636, 'Purple Mountainheath', 79, 601);
insert into Crop (crop_id, Name, health_id, yield_id) values (637, 'Rim Lichen', 75, 561);
insert into Crop (crop_id, Name, health_id, yield_id) values (638, 'Melic Mannagrass', 37, 170);
insert into Crop (crop_id, Name, health_id, yield_id) values (639, 'Coenogonium Lichen', 38, 910);
insert into Crop (crop_id, Name, health_id, yield_id) values (640, 'Densespike Blazing Star', 49, 406);
insert into Crop (crop_id, Name, health_id, yield_id) values (641, 'American Tarwort', 23, 594);
insert into Crop (crop_id, Name, health_id, yield_id) values (642, 'Saltmeadow Cordgrass', 1, 656);
insert into Crop (crop_id, Name, health_id, yield_id) values (643, 'Starbur', 120, 321);
insert into Crop (crop_id, Name, health_id, yield_id) values (644, 'Coleman''s Crested Coralroot', 118, 633);
insert into Crop (crop_id, Name, health_id, yield_id) values (645, 'Least Adderstongue', 125, 472);
insert into Crop (crop_id, Name, health_id, yield_id) values (646, 'Wild Tantan', 39, 888);
insert into Crop (crop_id, Name, health_id, yield_id) values (647, 'Kaibab Plateau Indian Paintbrush', 65, 930);
insert into Crop (crop_id, Name, health_id, yield_id) values (648, 'Footsteps Of Spring', 43, 701);
insert into Crop (crop_id, Name, health_id, yield_id) values (649, 'Tomasellia Lichen', 45, 998);
insert into Crop (crop_id, Name, health_id, yield_id) values (650, 'Woman''s Tobacco', 24, 112);
insert into Crop (crop_id, Name, health_id, yield_id) values (651, 'Virginia Wakerobin', 25, 539);
insert into Crop (crop_id, Name, health_id, yield_id) values (652, 'Lady''s Tresses', 16, 784);
insert into Crop (crop_id, Name, health_id, yield_id) values (653, 'Mandarin Lime', 16, 661);
insert into Crop (crop_id, Name, health_id, yield_id) values (654, 'Smallhead Sneezeweed', 52, 681);
insert into Crop (crop_id, Name, health_id, yield_id) values (655, 'Creeping Bentgrass', 71, 177);
insert into Crop (crop_id, Name, health_id, yield_id) values (656, 'Hooded Orchid', 121, 661);
insert into Crop (crop_id, Name, health_id, yield_id) values (657, 'Hybrid Oak', 130, 116);
insert into Crop (crop_id, Name, health_id, yield_id) values (658, 'Kisses', 29, 232);
insert into Crop (crop_id, Name, health_id, yield_id) values (659, 'Swamp Peperomia', 12, 280);
insert into Crop (crop_id, Name, health_id, yield_id) values (660, 'Pinewoods Fingergrass', 21, 859);
insert into Crop (crop_id, Name, health_id, yield_id) values (661, 'Swamp Saltbush', 26, 498);
insert into Crop (crop_id, Name, health_id, yield_id) values (662, 'Violet Tree', 51, 968);
insert into Crop (crop_id, Name, health_id, yield_id) values (663, 'Heartleaf Keckiella', 41, 296);
insert into Crop (crop_id, Name, health_id, yield_id) values (664, 'Whitewicky', 98, 804);
insert into Crop (crop_id, Name, health_id, yield_id) values (665, 'Clubmoss Mousetail', 98, 257);
insert into Crop (crop_id, Name, health_id, yield_id) values (666, 'Sarcosagium Lichen', 83, 172);
insert into Crop (crop_id, Name, health_id, yield_id) values (667, 'Italian Viper''s Bugloss', 73, 339);
insert into Crop (crop_id, Name, health_id, yield_id) values (668, 'Devil''s Bite', 106, 521);
insert into Crop (crop_id, Name, health_id, yield_id) values (669, 'Lane Mountain Milkvetch', 137, 960);
insert into Crop (crop_id, Name, health_id, yield_id) values (670, 'Shenandoah Pore Lichen', 140, 807);
insert into Crop (crop_id, Name, health_id, yield_id) values (671, 'Leafy Broom', 116, 600);
insert into Crop (crop_id, Name, health_id, yield_id) values (672, 'Longflowered Veldtgrass', 21, 95);
insert into Crop (crop_id, Name, health_id, yield_id) values (673, 'Florida Horsenettle', 24, 512);
insert into Crop (crop_id, Name, health_id, yield_id) values (674, 'Fountain Thistle', 14, 167);
insert into Crop (crop_id, Name, health_id, yield_id) values (675, 'Starry Rosinweed', 60, 217);
insert into Crop (crop_id, Name, health_id, yield_id) values (676, 'Feather River Monardella', 137, 324);
insert into Crop (crop_id, Name, health_id, yield_id) values (677, 'Carolina Wild Petunia', 147, 38);
insert into Crop (crop_id, Name, health_id, yield_id) values (678, 'Scarlet Beeblossom', 48, 116);
insert into Crop (crop_id, Name, health_id, yield_id) values (679, 'Sarcographa Lichen', 99, 614);
insert into Crop (crop_id, Name, health_id, yield_id) values (680, 'Common Juniper', 1, 728);
insert into Crop (crop_id, Name, health_id, yield_id) values (681, 'Clubmoss', 4, 856);
insert into Crop (crop_id, Name, health_id, yield_id) values (682, 'Crested Sedge', 114, 411);
insert into Crop (crop_id, Name, health_id, yield_id) values (683, 'Ovate Tetrodontium Moss', 85, 858);
insert into Crop (crop_id, Name, health_id, yield_id) values (684, 'Pinkfringe', 146, 44);
insert into Crop (crop_id, Name, health_id, yield_id) values (685, 'Low Goosefoot', 66, 669);
insert into Crop (crop_id, Name, health_id, yield_id) values (686, 'Eaton''s Lipfern', 95, 616);
insert into Crop (crop_id, Name, health_id, yield_id) values (687, 'California Ash', 36, 958);
insert into Crop (crop_id, Name, health_id, yield_id) values (688, 'Hybrid Oak', 97, 18);
insert into Crop (crop_id, Name, health_id, yield_id) values (689, 'Fernleaf Yellow False Foxglove', 136, 952);
insert into Crop (crop_id, Name, health_id, yield_id) values (690, 'Vancouver Porotrichum Moss', 25, 926);
insert into Crop (crop_id, Name, health_id, yield_id) values (691, 'Northern California Walnut', 37, 570);
insert into Crop (crop_id, Name, health_id, yield_id) values (692, 'Birchleaf Mountain Mahogany', 101, 339);
insert into Crop (crop_id, Name, health_id, yield_id) values (693, 'Yellow Bloodleaf', 13, 689);
insert into Crop (crop_id, Name, health_id, yield_id) values (694, 'European Searocket', 82, 989);
insert into Crop (crop_id, Name, health_id, yield_id) values (695, 'Spotted Gum', 139, 265);
insert into Crop (crop_id, Name, health_id, yield_id) values (696, 'Tree Lavatera', 90, 922);
insert into Crop (crop_id, Name, health_id, yield_id) values (697, 'White Mountain Ragwort', 78, 800);
insert into Crop (crop_id, Name, health_id, yield_id) values (698, 'Abert''s Buckwheat', 8, 642);
insert into Crop (crop_id, Name, health_id, yield_id) values (699, 'Mt. Eddy Buckwheat', 119, 787);
insert into Crop (crop_id, Name, health_id, yield_id) values (700, 'Scalloped Milkwort', 138, 130);
insert into Crop (crop_id, Name, health_id, yield_id) values (701, 'Smooth False Buttonweed', 4, 686);
insert into Crop (crop_id, Name, health_id, yield_id) values (702, 'Moss Campion', 97, 913);
insert into Crop (crop_id, Name, health_id, yield_id) values (703, 'Littleleaf Mountain Mahogany', 130, 461);
insert into Crop (crop_id, Name, health_id, yield_id) values (704, 'Kern River Fleabane', 96, 697);
insert into Crop (crop_id, Name, health_id, yield_id) values (705, 'Myrionora', 89, 221);
insert into Crop (crop_id, Name, health_id, yield_id) values (706, 'Podistera', 51, 992);
insert into Crop (crop_id, Name, health_id, yield_id) values (707, 'Chocolate Lily', 109, 481);
insert into Crop (crop_id, Name, health_id, yield_id) values (708, 'Flatspine Stickseed', 36, 846);
insert into Crop (crop_id, Name, health_id, yield_id) values (709, 'Mann''s Island Spleenwort', 133, 913);
insert into Crop (crop_id, Name, health_id, yield_id) values (710, 'Maiden Blue Eyed Mary', 101, 957);
insert into Crop (crop_id, Name, health_id, yield_id) values (711, 'Blistered Navel Lichen', 72, 445);
insert into Crop (crop_id, Name, health_id, yield_id) values (712, 'Palo De Vaca', 87, 768);
insert into Crop (crop_id, Name, health_id, yield_id) values (713, 'Amazonvine', 109, 527);
insert into Crop (crop_id, Name, health_id, yield_id) values (714, 'Orcutt''s Brodiaea', 126, 337);
insert into Crop (crop_id, Name, health_id, yield_id) values (715, 'Leatherstem', 116, 764);
insert into Crop (crop_id, Name, health_id, yield_id) values (716, 'Mojave Woodyaster', 19, 791);
insert into Crop (crop_id, Name, health_id, yield_id) values (717, 'Bent Two-whorl Buckwheat', 77, 880);
insert into Crop (crop_id, Name, health_id, yield_id) values (718, 'Wood''s Hau Kuahiwi', 96, 820);
insert into Crop (crop_id, Name, health_id, yield_id) values (719, 'White Doll''s Daisy', 95, 267);
insert into Crop (crop_id, Name, health_id, yield_id) values (720, 'Scrambling Nightshade', 39, 327);
insert into Crop (crop_id, Name, health_id, yield_id) values (721, 'Fineflower Gilia', 56, 654);
insert into Crop (crop_id, Name, health_id, yield_id) values (722, 'Feathery False Lily Of The Valley', 22, 969);
insert into Crop (crop_id, Name, health_id, yield_id) values (723, 'Larger Western Mountain Aster', 39, 244);
insert into Crop (crop_id, Name, health_id, yield_id) values (724, 'Pygmy Fringetree', 87, 914);
insert into Crop (crop_id, Name, health_id, yield_id) values (725, 'Shining Blazingstar', 99, 116);
insert into Crop (crop_id, Name, health_id, yield_id) values (726, 'Sand Spikerush', 72, 924);
insert into Crop (crop_id, Name, health_id, yield_id) values (727, 'Hoary Skullcap', 70, 57);
insert into Crop (crop_id, Name, health_id, yield_id) values (728, 'Stinking Milkvetch', 69, 426);
insert into Crop (crop_id, Name, health_id, yield_id) values (729, 'Trichodon Moss', 121, 377);
insert into Crop (crop_id, Name, health_id, yield_id) values (730, 'Sparselobe Grapefern', 115, 530);
insert into Crop (crop_id, Name, health_id, yield_id) values (731, 'Yellow Nailwort', 5, 23);
insert into Crop (crop_id, Name, health_id, yield_id) values (732, 'Loving Sedge', 131, 119);
insert into Crop (crop_id, Name, health_id, yield_id) values (733, 'Esteve''s Pincushion', 73, 243);
insert into Crop (crop_id, Name, health_id, yield_id) values (734, 'Dwarf Hesperochiron', 60, 301);
insert into Crop (crop_id, Name, health_id, yield_id) values (735, 'Woolly Brome', 59, 585);
insert into Crop (crop_id, Name, health_id, yield_id) values (736, 'Shortlobe Phacelia', 108, 454);
insert into Crop (crop_id, Name, health_id, yield_id) values (737, 'Piedmont Bedstraw', 32, 118);
insert into Crop (crop_id, Name, health_id, yield_id) values (738, 'Toothpetal Monkeyflower', 124, 305);
insert into Crop (crop_id, Name, health_id, yield_id) values (739, 'Abata Cola', 73, 88);
insert into Crop (crop_id, Name, health_id, yield_id) values (740, 'Sharp''s Weissia Moss', 47, 821);
insert into Crop (crop_id, Name, health_id, yield_id) values (741, 'Curtiss'' Nutrush', 132, 789);
insert into Crop (crop_id, Name, health_id, yield_id) values (742, 'Delta Bulrush', 59, 651);
insert into Crop (crop_id, Name, health_id, yield_id) values (743, 'Shelly''s Mousetail', 145, 668);
insert into Crop (crop_id, Name, health_id, yield_id) values (744, 'Low Bulrush', 47, 230);
insert into Crop (crop_id, Name, health_id, yield_id) values (745, 'Rothrock''s Keckiella', 92, 536);
insert into Crop (crop_id, Name, health_id, yield_id) values (746, 'Hart''s Tonguefern', 3, 55);
insert into Crop (crop_id, Name, health_id, yield_id) values (747, 'Howell''s Onion', 150, 681);
insert into Crop (crop_id, Name, health_id, yield_id) values (748, 'Lidpod', 9, 235);
insert into Crop (crop_id, Name, health_id, yield_id) values (749, 'Refugio Manzanita', 58, 889);
insert into Crop (crop_id, Name, health_id, yield_id) values (750, 'Pale Pseudoleskea Moss', 35, 446);
insert into Crop (crop_id, Name, health_id, yield_id) values (751, 'Western Mountain Kittentails', 139, 793);
insert into Crop (crop_id, Name, health_id, yield_id) values (752, 'Dicranum Moss', 84, 63);
insert into Crop (crop_id, Name, health_id, yield_id) values (753, 'Narrowleaf Bedstraw', 30, 521);
insert into Crop (crop_id, Name, health_id, yield_id) values (754, 'Pennsylvania Sedge', 140, 377);
insert into Crop (crop_id, Name, health_id, yield_id) values (755, 'Virginia Glasswort', 31, 451);
insert into Crop (crop_id, Name, health_id, yield_id) values (756, 'Maidenhair Spleenwort', 145, 574);
insert into Crop (crop_id, Name, health_id, yield_id) values (757, 'Wahine Noho Kula', 99, 567);
insert into Crop (crop_id, Name, health_id, yield_id) values (758, 'Hawai''ian Buttercup', 19, 380);
insert into Crop (crop_id, Name, health_id, yield_id) values (759, 'Destitute Rinodina Lichen', 61, 218);
insert into Crop (crop_id, Name, health_id, yield_id) values (760, 'Prairie Rosinweed', 113, 402);
insert into Crop (crop_id, Name, health_id, yield_id) values (761, 'Scratchbush', 43, 581);
insert into Crop (crop_id, Name, health_id, yield_id) values (762, 'Breadnut', 23, 44);
insert into Crop (crop_id, Name, health_id, yield_id) values (763, 'Leafless Beaked Lady Orchid', 3, 726);
insert into Crop (crop_id, Name, health_id, yield_id) values (764, 'Manac', 44, 773);
insert into Crop (crop_id, Name, health_id, yield_id) values (765, 'Orange Lichen', 40, 721);
insert into Crop (crop_id, Name, health_id, yield_id) values (766, 'Wydler''s Dancing-lady Orchid', 33, 794);
insert into Crop (crop_id, Name, health_id, yield_id) values (767, 'Felt Lichen', 137, 333);
insert into Crop (crop_id, Name, health_id, yield_id) values (768, 'Bluejoint', 71, 671);
insert into Crop (crop_id, Name, health_id, yield_id) values (769, 'Lichenothelia Lichen', 139, 917);
insert into Crop (crop_id, Name, health_id, yield_id) values (770, 'Skullcap', 56, 66);
insert into Crop (crop_id, Name, health_id, yield_id) values (771, 'Sampson''s Snakeroot', 113, 817);
insert into Crop (crop_id, Name, health_id, yield_id) values (772, 'Packard''s Desertparsley', 87, 285);
insert into Crop (crop_id, Name, health_id, yield_id) values (773, 'Giant Rhubarb', 63, 328);
insert into Crop (crop_id, Name, health_id, yield_id) values (774, 'Griffith''s Oedipodium Moss', 31, 786);
insert into Crop (crop_id, Name, health_id, yield_id) values (775, 'Serviceberry', 77, 203);
insert into Crop (crop_id, Name, health_id, yield_id) values (776, 'Kellogg''s Yampah', 49, 509);
insert into Crop (crop_id, Name, health_id, yield_id) values (777, 'Oleander Fern', 51, 323);
insert into Crop (crop_id, Name, health_id, yield_id) values (778, 'Heller''s Rosette Grass', 104, 621);
insert into Crop (crop_id, Name, health_id, yield_id) values (779, 'Spiked Centaury', 124, 884);
insert into Crop (crop_id, Name, health_id, yield_id) values (780, 'Rattlesnake Fern', 93, 775);
insert into Crop (crop_id, Name, health_id, yield_id) values (781, 'Kauri', 110, 408);
insert into Crop (crop_id, Name, health_id, yield_id) values (782, 'Panicum', 143, 168);
insert into Crop (crop_id, Name, health_id, yield_id) values (783, 'Littlehead Nutrush', 137, 164);
insert into Crop (crop_id, Name, health_id, yield_id) values (784, 'Radish', 73, 69);
insert into Crop (crop_id, Name, health_id, yield_id) values (785, 'Polytrichum Moss', 52, 571);
insert into Crop (crop_id, Name, health_id, yield_id) values (786, 'Dotted Bristle Fern', 143, 809);
insert into Crop (crop_id, Name, health_id, yield_id) values (787, 'Devil''s-pepper', 57, 497);
insert into Crop (crop_id, Name, health_id, yield_id) values (788, 'Subalpine Monkeyflower', 24, 222);
insert into Crop (crop_id, Name, health_id, yield_id) values (789, 'Hillside Gooseberry', 87, 473);
insert into Crop (crop_id, Name, health_id, yield_id) values (790, 'Snow Lichen', 142, 761);
insert into Crop (crop_id, Name, health_id, yield_id) values (791, 'Queen Anne''s Lace', 65, 750);
insert into Crop (crop_id, Name, health_id, yield_id) values (792, 'Northern Eyebright', 125, 279);
insert into Crop (crop_id, Name, health_id, yield_id) values (793, 'Faurie''s Panicgrass', 93, 703);
insert into Crop (crop_id, Name, health_id, yield_id) values (794, 'Pore Lichen', 120, 208);
insert into Crop (crop_id, Name, health_id, yield_id) values (795, 'Dunbar''s Hawthorn', 1, 799);
insert into Crop (crop_id, Name, health_id, yield_id) values (796, 'Sticky Lovegrass', 117, 84);
insert into Crop (crop_id, Name, health_id, yield_id) values (797, 'Oregon Semaphoregrass', 76, 741);
insert into Crop (crop_id, Name, health_id, yield_id) values (798, 'Thelenella Lichen', 83, 151);
insert into Crop (crop_id, Name, health_id, yield_id) values (799, 'Gulf Graytwig', 46, 275);
insert into Crop (crop_id, Name, health_id, yield_id) values (800, 'Bluefly Honeysuckle', 76, 276);
insert into Crop (crop_id, Name, health_id, yield_id) values (801, 'Bengal Coffee', 55, 294);
insert into Crop (crop_id, Name, health_id, yield_id) values (802, 'Link''s Maiden Fern', 132, 939);
insert into Crop (crop_id, Name, health_id, yield_id) values (803, 'Waghorne''s Pore Lichen', 16, 542);
insert into Crop (crop_id, Name, health_id, yield_id) values (804, 'Texas Sunnybell', 28, 501);
insert into Crop (crop_id, Name, health_id, yield_id) values (805, 'China Doll', 13, 845);
insert into Crop (crop_id, Name, health_id, yield_id) values (806, 'Montezuma Melicgrass', 19, 667);
insert into Crop (crop_id, Name, health_id, yield_id) values (807, 'Hirtella', 69, 855);
insert into Crop (crop_id, Name, health_id, yield_id) values (808, 'Coconut Paspalum', 65, 47);
insert into Crop (crop_id, Name, health_id, yield_id) values (809, 'Gmelina', 83, 89);
insert into Crop (crop_id, Name, health_id, yield_id) values (810, 'Hyacinth Meadow Garlic', 73, 618);
insert into Crop (crop_id, Name, health_id, yield_id) values (811, 'Pioneer Rockcress', 115, 985);
insert into Crop (crop_id, Name, health_id, yield_id) values (812, 'Molendoa Moss', 49, 786);
insert into Crop (crop_id, Name, health_id, yield_id) values (813, 'Pasto Micael', 9, 69);
insert into Crop (crop_id, Name, health_id, yield_id) values (814, 'Peruvian Paspalum', 15, 30);
insert into Crop (crop_id, Name, health_id, yield_id) values (815, 'Eared Veinfern', 93, 376);
insert into Crop (crop_id, Name, health_id, yield_id) values (816, 'Ixeris', 125, 345);
insert into Crop (crop_id, Name, health_id, yield_id) values (817, 'Fraser Meadow Garlic', 8, 541);
insert into Crop (crop_id, Name, health_id, yield_id) values (818, 'Sticky Cinquefoil', 85, 85);
insert into Crop (crop_id, Name, health_id, yield_id) values (819, 'Greentwig', 118, 469);
insert into Crop (crop_id, Name, health_id, yield_id) values (820, 'Netted Milkvine', 1, 619);
insert into Crop (crop_id, Name, health_id, yield_id) values (821, 'Piedmont Blacksenna', 46, 618);
insert into Crop (crop_id, Name, health_id, yield_id) values (822, 'Koshum', 60, 512);
insert into Crop (crop_id, Name, health_id, yield_id) values (823, 'Hall''s Rush', 19, 456);
insert into Crop (crop_id, Name, health_id, yield_id) values (824, 'Clearwater Phlox', 69, 779);
insert into Crop (crop_id, Name, health_id, yield_id) values (825, 'Sierra Currant', 78, 152);
insert into Crop (crop_id, Name, health_id, yield_id) values (826, 'Kura Clover', 50, 603);
insert into Crop (crop_id, Name, health_id, yield_id) values (827, 'Spoonleaf Buckwheat', 36, 790);
insert into Crop (crop_id, Name, health_id, yield_id) values (828, 'Narrowleaf Bittercress', 44, 714);
insert into Crop (crop_id, Name, health_id, yield_id) values (829, 'Ground Orchid', 89, 990);
insert into Crop (crop_id, Name, health_id, yield_id) values (830, 'Purple Mountainheath', 108, 866);
insert into Crop (crop_id, Name, health_id, yield_id) values (831, 'Roble Colorado', 95, 646);
insert into Crop (crop_id, Name, health_id, yield_id) values (832, 'Uruguayan Pampas Grass', 61, 19);
insert into Crop (crop_id, Name, health_id, yield_id) values (833, 'Prairie Bluebells', 79, 859);
insert into Crop (crop_id, Name, health_id, yield_id) values (834, 'Pricklyleaf', 110, 833);
insert into Crop (crop_id, Name, health_id, yield_id) values (835, 'Rollins'' Twinpod', 51, 179);
insert into Crop (crop_id, Name, health_id, yield_id) values (836, 'Chilean Gunnera', 99, 433);
insert into Crop (crop_id, Name, health_id, yield_id) values (837, 'Hare''s Ear Mustard', 99, 302);
insert into Crop (crop_id, Name, health_id, yield_id) values (838, 'Prairie Violet', 104, 194);
insert into Crop (crop_id, Name, health_id, yield_id) values (839, 'Luisierella Moss', 116, 113);
insert into Crop (crop_id, Name, health_id, yield_id) values (840, 'Spleenwort', 4, 57);
insert into Crop (crop_id, Name, health_id, yield_id) values (841, 'Spadeleaf', 65, 679);
insert into Crop (crop_id, Name, health_id, yield_id) values (842, 'Pyxidanthera', 47, 417);
insert into Crop (crop_id, Name, health_id, yield_id) values (843, 'Abietenella Moss', 137, 904);
insert into Crop (crop_id, Name, health_id, yield_id) values (844, 'Goldenfleece', 25, 445);
insert into Crop (crop_id, Name, health_id, yield_id) values (845, 'California Fagonbush', 141, 841);
insert into Crop (crop_id, Name, health_id, yield_id) values (846, 'Lake County Mock Stonecrop', 28, 466);
insert into Crop (crop_id, Name, health_id, yield_id) values (847, 'Blakley''s Spineflower', 5, 338);
insert into Crop (crop_id, Name, health_id, yield_id) values (848, 'Guiana Plum', 10, 754);
insert into Crop (crop_id, Name, health_id, yield_id) values (849, 'Silver-top Gimlet', 141, 422);
insert into Crop (crop_id, Name, health_id, yield_id) values (850, 'Wild Cinnamon', 21, 215);
insert into Crop (crop_id, Name, health_id, yield_id) values (851, 'Giant Airplant', 24, 452);
insert into Crop (crop_id, Name, health_id, yield_id) values (852, 'Hedgehog Cactus', 16, 955);
insert into Crop (crop_id, Name, health_id, yield_id) values (853, 'Clappertonia', 83, 621);
insert into Crop (crop_id, Name, health_id, yield_id) values (854, 'Cosmosflower Beggarticks', 18, 484);
insert into Crop (crop_id, Name, health_id, yield_id) values (855, 'Sweet Signalgrass', 96, 223);
insert into Crop (crop_id, Name, health_id, yield_id) values (856, 'Idaho Twinpod', 97, 195);
insert into Crop (crop_id, Name, health_id, yield_id) values (857, 'Starflower', 95, 941);
insert into Crop (crop_id, Name, health_id, yield_id) values (858, 'Idaho Bladderpod', 12, 749);
insert into Crop (crop_id, Name, health_id, yield_id) values (859, 'Purplestem Taro', 141, 470);
insert into Crop (crop_id, Name, health_id, yield_id) values (860, 'Cracked Lichen', 125, 697);
insert into Crop (crop_id, Name, health_id, yield_id) values (861, 'Rosy Palafox', 24, 909);
insert into Crop (crop_id, Name, health_id, yield_id) values (862, 'Waxflower Shinleaf', 15, 369);
insert into Crop (crop_id, Name, health_id, yield_id) values (863, 'Greentinge Indian Paintbrush', 131, 602);
insert into Crop (crop_id, Name, health_id, yield_id) values (864, 'Caribbean Spiritweed', 69, 36);
insert into Crop (crop_id, Name, health_id, yield_id) values (865, 'Stemless Four-nerve Daisy', 77, 115);
insert into Crop (crop_id, Name, health_id, yield_id) values (866, 'Edwards Plateau Sedge', 42, 206);
insert into Crop (crop_id, Name, health_id, yield_id) values (867, 'Lady Tulip', 37, 480);
insert into Crop (crop_id, Name, health_id, yield_id) values (868, 'Perennial Horsegram', 54, 971);
insert into Crop (crop_id, Name, health_id, yield_id) values (869, 'Arboles Milkvetch', 92, 968);
insert into Crop (crop_id, Name, health_id, yield_id) values (870, 'Elegant Groundsel', 73, 545);
insert into Crop (crop_id, Name, health_id, yield_id) values (871, 'Lempholemma Lichen', 41, 251);
insert into Crop (crop_id, Name, health_id, yield_id) values (872, 'Lyall''s Goldenweed', 118, 616);
insert into Crop (crop_id, Name, health_id, yield_id) values (873, 'Stiff Willowherb', 72, 711);
insert into Crop (crop_id, Name, health_id, yield_id) values (874, 'Gridscale Maiden Fern', 42, 831);
insert into Crop (crop_id, Name, health_id, yield_id) values (875, 'Cushion Buckwheat', 143, 976);
insert into Crop (crop_id, Name, health_id, yield_id) values (876, 'Lanahale', 20, 393);
insert into Crop (crop_id, Name, health_id, yield_id) values (877, 'Dunegrass', 35, 90);
insert into Crop (crop_id, Name, health_id, yield_id) values (878, 'Howell''s Jewelflower', 146, 576);
insert into Crop (crop_id, Name, health_id, yield_id) values (879, 'Crested Anoda', 29, 863);
insert into Crop (crop_id, Name, health_id, yield_id) values (880, 'Alakai Swamp Island-daisy', 44, 172);
insert into Crop (crop_id, Name, health_id, yield_id) values (881, 'Kozlov''s Pterygoneurum Moss', 126, 593);
insert into Crop (crop_id, Name, health_id, yield_id) values (882, 'California Licorice-root', 43, 579);
insert into Crop (crop_id, Name, health_id, yield_id) values (883, 'Roundleaf Thoroughwort', 135, 494);
insert into Crop (crop_id, Name, health_id, yield_id) values (884, 'Commelina', 17, 412);
insert into Crop (crop_id, Name, health_id, yield_id) values (885, 'Pentzia', 64, 929);
insert into Crop (crop_id, Name, health_id, yield_id) values (886, 'Hungarian Vetch', 73, 689);
insert into Crop (crop_id, Name, health_id, yield_id) values (887, 'Three Peaks Jewelflower', 88, 989);
insert into Crop (crop_id, Name, health_id, yield_id) values (888, 'Texas Heliotrope', 150, 899);
insert into Crop (crop_id, Name, health_id, yield_id) values (889, 'Convoluted Barbula Moss', 77, 69);
insert into Crop (crop_id, Name, health_id, yield_id) values (890, 'Burr Daisytree', 145, 316);
insert into Crop (crop_id, Name, health_id, yield_id) values (891, 'Grapefern', 115, 800);
insert into Crop (crop_id, Name, health_id, yield_id) values (892, 'Yellow Columbine', 150, 194);
insert into Crop (crop_id, Name, health_id, yield_id) values (893, 'White Cypress-pine', 40, 439);
insert into Crop (crop_id, Name, health_id, yield_id) values (894, 'Olokele Valley Melicope', 21, 611);
insert into Crop (crop_id, Name, health_id, yield_id) values (895, 'Pearly Pussytoes', 121, 299);
insert into Crop (crop_id, Name, health_id, yield_id) values (896, 'Bailey''s Pseudoleskea Moss', 19, 191);
insert into Crop (crop_id, Name, health_id, yield_id) values (897, 'Ornduff''s Meadowfoam', 56, 152);
insert into Crop (crop_id, Name, health_id, yield_id) values (898, 'Suksdorf''s Spikerush', 107, 506);
insert into Crop (crop_id, Name, health_id, yield_id) values (899, 'Bluebill', 33, 384);
insert into Crop (crop_id, Name, health_id, yield_id) values (900, 'Microsteris', 53, 313);
insert into Crop (crop_id, Name, health_id, yield_id) values (901, 'Sunflower', 1, 786);
insert into Crop (crop_id, Name, health_id, yield_id) values (902, 'Lindheimer''s Globeberry', 94, 984);
insert into Crop (crop_id, Name, health_id, yield_id) values (903, 'Common Knotweed', 66, 634);
insert into Crop (crop_id, Name, health_id, yield_id) values (904, 'Iranian Knapweed', 141, 924);
insert into Crop (crop_id, Name, health_id, yield_id) values (905, 'Heartsepal Buckwheat', 8, 795);
insert into Crop (crop_id, Name, health_id, yield_id) values (906, 'Na''ena''e ''ula', 59, 683);
insert into Crop (crop_id, Name, health_id, yield_id) values (907, 'Canadian Rim Lichen', 79, 501);
insert into Crop (crop_id, Name, health_id, yield_id) values (908, 'Parry''s Milkvetch', 114, 553);
insert into Crop (crop_id, Name, health_id, yield_id) values (909, 'Slender Fleabane', 1, 233);
insert into Crop (crop_id, Name, health_id, yield_id) values (910, 'Phaeographina Lichen', 85, 255);
insert into Crop (crop_id, Name, health_id, yield_id) values (911, 'Burro Blanco', 44, 430);
insert into Crop (crop_id, Name, health_id, yield_id) values (912, 'Immersed Physcomitrium Moss', 15, 807);
insert into Crop (crop_id, Name, health_id, yield_id) values (913, 'Daucosma', 142, 192);
insert into Crop (crop_id, Name, health_id, yield_id) values (914, 'Strawberry Cactus', 43, 844);
insert into Crop (crop_id, Name, health_id, yield_id) values (915, 'Rusty Molly', 72, 40);
insert into Crop (crop_id, Name, health_id, yield_id) values (916, 'Rasp-leaf Pelargonium', 103, 650);
insert into Crop (crop_id, Name, health_id, yield_id) values (917, 'Asian Crabgrass', 45, 797);
insert into Crop (crop_id, Name, health_id, yield_id) values (918, 'Blue Woodruff', 56, 279);
insert into Crop (crop_id, Name, health_id, yield_id) values (919, 'Arawnig', 4, 271);
insert into Crop (crop_id, Name, health_id, yield_id) values (920, 'South American Tobacco', 107, 242);
insert into Crop (crop_id, Name, health_id, yield_id) values (921, 'Plains Onion', 24, 319);
insert into Crop (crop_id, Name, health_id, yield_id) values (922, 'Simpleleaf Chastetree', 29, 149);
insert into Crop (crop_id, Name, health_id, yield_id) values (923, 'Julella Lichen', 140, 33);
insert into Crop (crop_id, Name, health_id, yield_id) values (924, 'Arizona Pottia Moss', 52, 384);
insert into Crop (crop_id, Name, health_id, yield_id) values (925, 'Leiberg''s Bittercress', 30, 919);
insert into Crop (crop_id, Name, health_id, yield_id) values (926, 'Baldwin''s Ironweed', 56, 249);
insert into Crop (crop_id, Name, health_id, yield_id) values (927, 'Cupseed', 31, 99);
insert into Crop (crop_id, Name, health_id, yield_id) values (928, 'Silky Deerweed', 81, 669);
insert into Crop (crop_id, Name, health_id, yield_id) values (929, 'Dotted Smartweed', 7, 878);
insert into Crop (crop_id, Name, health_id, yield_id) values (930, 'Amazon Waterlily', 57, 81);
insert into Crop (crop_id, Name, health_id, yield_id) values (931, 'Woollybutt', 29, 84);
insert into Crop (crop_id, Name, health_id, yield_id) values (932, 'Chalice Lichen', 111, 974);
insert into Crop (crop_id, Name, health_id, yield_id) values (933, 'Smooth Rose', 128, 650);
insert into Crop (crop_id, Name, health_id, yield_id) values (934, 'Rim Lichen', 110, 891);
insert into Crop (crop_id, Name, health_id, yield_id) values (935, 'Sulphur-flower Buckwheat', 27, 145);
insert into Crop (crop_id, Name, health_id, yield_id) values (936, 'San Antonio Hills Monardella', 118, 350);
insert into Crop (crop_id, Name, health_id, yield_id) values (937, 'White Edge Sedge', 64, 795);
insert into Crop (crop_id, Name, health_id, yield_id) values (938, 'Low Pussytoes', 17, 174);
insert into Crop (crop_id, Name, health_id, yield_id) values (939, 'Stiff Bristle Fern', 141, 987);
insert into Crop (crop_id, Name, health_id, yield_id) values (940, 'Longtip Lacebark', 9, 421);
insert into Crop (crop_id, Name, health_id, yield_id) values (941, 'Douglas'' Bladderpod', 86, 438);
insert into Crop (crop_id, Name, health_id, yield_id) values (942, 'Bourbon Rose', 52, 642);
insert into Crop (crop_id, Name, health_id, yield_id) values (943, 'Jaboncillo', 107, 761);
insert into Crop (crop_id, Name, health_id, yield_id) values (944, 'Guianese Colicwood', 35, 403);
insert into Crop (crop_id, Name, health_id, yield_id) values (945, 'Shrubland Dubautia', 24, 442);
insert into Crop (crop_id, Name, health_id, yield_id) values (946, 'Dogtooth Violet', 117, 972);
insert into Crop (crop_id, Name, health_id, yield_id) values (947, 'West Indian Sumac', 31, 909);
insert into Crop (crop_id, Name, health_id, yield_id) values (948, 'Silver Cinquefoil', 95, 592);
insert into Crop (crop_id, Name, health_id, yield_id) values (949, 'Yukon Wheatgrass', 48, 661);
insert into Crop (crop_id, Name, health_id, yield_id) values (950, 'Trailing Shrubverbena', 131, 953);
insert into Crop (crop_id, Name, health_id, yield_id) values (951, 'Prairie Hawthorn', 8, 511);
insert into Crop (crop_id, Name, health_id, yield_id) values (952, 'Wheeler''s Sphagnum', 65, 273);
insert into Crop (crop_id, Name, health_id, yield_id) values (953, 'Sunray', 26, 659);
insert into Crop (crop_id, Name, health_id, yield_id) values (954, 'Purple Foxglove', 34, 259);
insert into Crop (crop_id, Name, health_id, yield_id) values (955, 'Stiffleaf False Goldenaster', 105, 413);
insert into Crop (crop_id, Name, health_id, yield_id) values (956, 'Serianthes', 80, 275);
insert into Crop (crop_id, Name, health_id, yield_id) values (957, 'Aparejograss', 27, 946);
insert into Crop (crop_id, Name, health_id, yield_id) values (958, 'Hillside Vervain', 73, 627);
insert into Crop (crop_id, Name, health_id, yield_id) values (959, 'Correll''s Snakewood', 83, 483);
insert into Crop (crop_id, Name, health_id, yield_id) values (960, 'Illinois Horse-gentian', 140, 514);
insert into Crop (crop_id, Name, health_id, yield_id) values (961, 'Oceanspray', 20, 180);
insert into Crop (crop_id, Name, health_id, yield_id) values (962, 'Woollyhead Clover', 124, 615);
insert into Crop (crop_id, Name, health_id, yield_id) values (963, 'Orange Agoseris', 86, 976);
insert into Crop (crop_id, Name, health_id, yield_id) values (964, 'Aguinaldo Blanco', 88, 698);
insert into Crop (crop_id, Name, health_id, yield_id) values (965, 'Feather Reed Grass', 118, 392);
insert into Crop (crop_id, Name, health_id, yield_id) values (966, 'Mendocino Lessingia', 16, 918);
insert into Crop (crop_id, Name, health_id, yield_id) values (967, 'Texan Syrrhopodon Moss', 64, 311);
insert into Crop (crop_id, Name, health_id, yield_id) values (968, 'White Trillium', 114, 109);
insert into Crop (crop_id, Name, health_id, yield_id) values (969, 'Forest Clermontia', 93, 308);
insert into Crop (crop_id, Name, health_id, yield_id) values (970, 'Streambank Lipfern', 109, 346);
insert into Crop (crop_id, Name, health_id, yield_id) values (971, 'Whited''s Fissurewort', 53, 227);
insert into Crop (crop_id, Name, health_id, yield_id) values (972, 'Fleshy Starwort', 131, 117);
insert into Crop (crop_id, Name, health_id, yield_id) values (973, 'Pacific Lousewort', 97, 888);
insert into Crop (crop_id, Name, health_id, yield_id) values (974, 'Corymb Rose', 74, 867);
insert into Crop (crop_id, Name, health_id, yield_id) values (975, 'Dieter''s Erigeron', 80, 950);
insert into Crop (crop_id, Name, health_id, yield_id) values (976, 'Fringed False Hellebore', 78, 496);
insert into Crop (crop_id, Name, health_id, yield_id) values (977, 'Goosefoot', 102, 635);
insert into Crop (crop_id, Name, health_id, yield_id) values (978, 'Pacific Trillium', 81, 196);
insert into Crop (crop_id, Name, health_id, yield_id) values (979, 'Sterculia', 112, 533);
insert into Crop (crop_id, Name, health_id, yield_id) values (980, 'Shortleaf Liveforever', 35, 237);
insert into Crop (crop_id, Name, health_id, yield_id) values (981, 'Oysterleaf', 146, 188);
insert into Crop (crop_id, Name, health_id, yield_id) values (982, 'Broadleaf Wild Leek', 14, 134);
insert into Crop (crop_id, Name, health_id, yield_id) values (983, 'Silky Cinquefoil', 72, 146);
insert into Crop (crop_id, Name, health_id, yield_id) values (984, 'Scouler''s Surfgrass', 147, 520);
insert into Crop (crop_id, Name, health_id, yield_id) values (985, 'Esteve''s Pincushion', 11, 143);
insert into Crop (crop_id, Name, health_id, yield_id) values (986, 'Kalinia Grass', 4, 811);
insert into Crop (crop_id, Name, health_id, yield_id) values (987, 'Stalkgrain Sedge', 145, 672);
insert into Crop (crop_id, Name, health_id, yield_id) values (988, 'Dwarf Waterclover', 97, 516);
insert into Crop (crop_id, Name, health_id, yield_id) values (989, 'Cleveland''s Beardtongue', 34, 728);
insert into Crop (crop_id, Name, health_id, yield_id) values (990, 'Wild Parsnip', 129, 864);
insert into Crop (crop_id, Name, health_id, yield_id) values (991, 'Lemmon''s Brickellbush', 43, 536);
insert into Crop (crop_id, Name, health_id, yield_id) values (992, 'Upland Larkspur', 127, 556);
insert into Crop (crop_id, Name, health_id, yield_id) values (993, 'Reticulate Cetraria Lichen', 41, 835);
insert into Crop (crop_id, Name, health_id, yield_id) values (994, 'Pointtip Twinpod', 110, 263);
insert into Crop (crop_id, Name, health_id, yield_id) values (995, 'Trachyxiphium Moss', 32, 736);
insert into Crop (crop_id, Name, health_id, yield_id) values (996, 'Greenleaf Ticktrefoil', 93, 751);
insert into Crop (crop_id, Name, health_id, yield_id) values (997, 'Turner''s Horseweed', 60, 309);
insert into Crop (crop_id, Name, health_id, yield_id) values (998, 'Grevillea', 35, 32);
insert into Crop (crop_id, Name, health_id, yield_id) values (999, 'Crown Brodiaea', 7, 390);
insert into Crop (crop_id, Name, health_id, yield_id) values (1000, 'Dry Calcareous Bryum Moss', 107, 783);
