-- Inserting diseases into the CropHealth table
INSERT INTO CropHealth (health_id, Diseases)
VALUES 
(1, 'Powdery Mildew'),
(2, 'Downy Mildew'),
(3, 'Rust'),
(4, 'Anthracnose'),
(5, 'Leaf Spot'),
(6, 'Botrytis Blight'),
(7, 'Fusarium Wilt'),
(8, 'Verticillium Wilt'),
(9, 'Phytophthora Root Rot'),
(10, 'Sclerotinia Rot'),
(11, 'Alternaria Blight'),
(12, 'Clubroot'),
(13, 'Bacterial Blight'),
(14, 'Bacterial Spot'),
(15, 'Bacterial Canker'),
(16, 'Crown Gall'),
(17, 'Fire Blight'),
(18, 'Citrus Canker'),
(19, 'Citrus Greening'),
(20, 'Black Spot (Rose)'),
(21, 'Gray Mold'),
(22, 'Root Knot Nematodes'),
(23, 'White Mold'),
(24, 'Smut'),
(25, 'Leaf Curl'),
(26, 'Apple Scab'),
(27, 'Apple Mosaic Virus'),
(28, 'Tomato Yellow Leaf Curl Virus'),
(29, 'Potato Late Blight'),
(30, 'Grape Downy Mildew'),
(31, 'Grape Anthracnose'),
(32, 'Tobacco Mosaic Virus'),
(33, 'Wheat Rust'),
(34, 'Barley Yellow Dwarf Virus'),
(35, 'Maize Dwarf Mosaic Virus'),
(36, 'Maize Streak Virus'),
(37, 'Rice Blast'),
(38, 'Rice Sheath Blight'),
(39, 'Citrus Tristeza Virus'),
(40, 'Banana Fusarium Wilt'),
(41, 'Fusarium Crown Rot'),
(42, 'Verticillium Wilt of Tomato'),
(43, 'Verticillium Wilt of Potato'),
(44, 'Verticillium Wilt of Cotton'),
(45, 'Peach Leaf Curl'),
(46, 'Pear Scab'),
(47, 'Pear Rust'),
(48, 'Pear Blister Mite'),
(49, 'Olive Anthracnose'),
(50, 'Olive Knot'),
(51, 'Olive Leaf Spot'),
(52, 'Olive Verticillium Wilt'),
(53, 'Pepper Bacterial Spot'),
(54, 'Pepper Anthracnose'),
(55, 'Pepper Powdery Mildew'),
(56, 'Pepper Yellow Leaf Curl Virus'),
(57, 'Potato Blackleg'),
(58, 'Potato Early Blight'),
(59, 'Potato Late Blight'),
(60, 'Potato Ring Rot'),
(61, 'Potato Common Scab'),
(62, 'Potato Tuber Blight'),
(63, 'Tomato Bacterial Canker'),
(64, 'Tomato Bacterial Speck'),
(65, 'Tomato Early Blight'),
(66, 'Tomato Late Blight'),
(67, 'Tomato Mosaic Virus'),
(68, 'Tomato Yellow Leaf Curl Virus'),
(69, 'Tomato Fusarium Wilt'),
(70, 'Tomato Verticillium Wilt'),
(71, 'Tomato Root Knot Nematode'),
(72, 'Cucumber Downy Mildew'),
(73, 'Cucumber Powdery Mildew'),
(74, 'Cucumber Anthracnose'),
(75, 'Cucumber Angular Leaf Spot'),
(76, 'Cucumber Fusarium Wilt'),
(77, 'Cucumber Verticillium Wilt'),
(78, 'Cucumber Root Knot Nematode'),
(79, 'Grape Black Rot'),
(80, 'Grape Crown Gall'),
(81, 'Grape Phylloxera'),
(82, 'Grape Powdery Mildew'),
(83, 'Grape Rust'),
(84, 'Grape Pierce''s Disease'),
(85, 'Grape Anthracnose'),
(86, 'Corn Smut'),
(87, 'Corn Rust'),
(88, 'Corn Stalk Rot'),
(89, 'Corn Ear Rot'),
(90, 'Corn Leaf Blight'),
(91, 'Corn Maize Dwarf Mosaic Virus'),
(92, 'Corn Maize Chlorotic Mottle Virus'),
(93, 'Corn Maize Streak Virus'),
(94, 'Rice Bacterial Leaf Blight'),
(95, 'Rice Sheath Rot'),
(96, 'Rice Tungro Virus'),
(97, 'Rice Bacterial Panicle Blight'),
(98, 'Rice Grain Smut'),
(99, 'Rice Sheath Blight'),
(100, 'Soybean Rust'),
(101, 'Soybean Cyst Nematode'),
(102, 'Soybean Seedling Blight'),
(103, 'Soybean Root Rot'),
(104, 'Soybean Mosaic Virus'),
(105, 'Soybean Powdery Mildew'),
(106, 'Cotton Verticillium Wilt'),
(107, 'Cotton Boll Rot'),
(108, 'Cotton Seedling Disease'),
(109, 'Cotton Fusarium Wilt'),
(110, 'Cotton Verticillium Wilt'),
(111, 'Cotton Root Knot Nematode'),
(112, 'Citrus Canker'),
(113, 'Citrus Scab'),
(114, 'Citrus Melanose'),
(115, 'Citrus Decline'),
(116, 'Citrus Root Rot'),
(117, 'Citrus Phytophthora Root Rot'),
(118, 'Citrus Alternaria Brown Spot'),
(119, 'Citrus Huanglongbing (HLB) Disease'),
(120, 'Apple Apple Scab'),
(121, 'Apple Powdery Mildew'),
(122, 'Apple Cedar Apple Rust'),
(123, 'Apple Fire Blight'),
(124, 'Apple Bitter Rot'),
(125, 'Apple Apple Mosaic Virus'),
(126, 'Pear Pear Scab'),
(127, 'Pear Pear Rust'),
(128, 'Pear Pear Blister Mite'),
(129, 'Pear Pear Decline'),
(130, 'Pear Fire Blight'),
(131, 'Pear Pear Canker'),
(132, 'Grape Powdery Mildew'),
(133, 'Grape Downy Mildew'),
(134, 'Grape Black Rot'),
(135, 'Grape Anthracnose'),
(136, 'Grape Crown Gall'),
(137, 'Grape Grapevine Fanleaf Virus'),
(138, 'Grape Pierce''s Disease'),
(139, 'Grape Botrytis Bunch Rot'),
(140, 'Strawberry Powdery Mildew'),
(141, 'Strawberry Leaf Spot'),
(142, 'Strawberry Anthracnose'),
(143, 'Strawberry Red Stele'),
(144, 'Strawberry Verticillium Wilt'),
(145, 'Strawberry Phytophthora Crown Rot'),
(146, 'Potato Late Blight'),
(147, 'Potato Early Blight'),
(148, 'Potato Common Scab'),
(149, 'Potato Blackleg'),
(150, 'Potato Fusarium Dry Rot');
